### ISSUE TITLE
19 Digit credit cars are coming

### ISSUE THREAD

**Issue by custa1200** [nosir/cleave.js#101]
as per title, it looks like maxlength is increasing to 19 digits for some common branded cards https://www.linkedin.com/pulse/19-digit-visas-2-digit-mastercards-doug-smith

**Comment by nosir** [comment]
Thanks, added an option to enable 19 digit checking:
https://github.com/nosir/cleave.js/blob/master/doc/options.md#creditcardstrictmode

**Comment by ivyyangthl** [comment]
When is this going to be released?
