### ISSUE TITLE
Currency type

### ISSUE THREAD

**Issue by custa1200** [nosir/cleave.js#102]
There is the ability to nave numerals that have nice spaces, but I tried prefix and there is no simple way to have a prefix of $(which only shows after beginning ti type and suffix of .00 unless until somebody types a . follows by the currency decimals number of characters. Seems like it would be a pretty common pattern people would like solved. Not sure where that would fit in the build process or if it is actually indeed possible.

**Comment by nosir** [comment]
Hi @custa1200, do you mean you want to have `$` as prefix and `.00` as the suffix?

**Comment by custa1200** [comment]
Well that would work for Australian currency and my use case but I am sure there are other formats for different currencies too, but thats what I am after. :)

**Comment by nosir** [comment]
Sorry, didn't quite understand the requirement, yes there has to be other formats for different currencies, can you please make an example the format that you want to achieve?
