### ISSUE TITLE
Accept or deny particular card types 

### ISSUE THREAD

**Issue by custa1200** [nosir/cleave.js#104]
The company I work for accepts certain card types. It would be great to easily limit to just those, i.e. Visa, Mastercard, AMEX, Diners and flag all others as invalid/not accepted.

**Comment by nosir** [comment]
The library will only focus on formatting input, so it won't support your user case, actually it allows you to enter incorrect credit card numbers.

Or maybe this can give you an option to flag the other cards:
https://github.com/nosir/cleave.js/blob/master/doc/options.md#oncreditcardtypechanged
