### ISSUE TITLE
Android chrome backspace can't erase delimiter issue

### ISSUE THREAD

**Issue by senja006** [nosir/cleave.js#106]
On chrome 52 for Android is not erased the card number.

**Comment by nosir** [comment]
Can you please explain more about it? Like in which case, you don't want it to remove the card number but it does.

**Comment by woble** [comment]
I believe what he means is that you can't erase input after it has been entered. I tried it as not too a while ago as well and using backspace on Android wouldn't delete anything unless you hit it a 3-5 times. Perhaps some delete is blocked by formatting function somehow (no idea how it works, haven't seen code).

**Comment by nosir** [comment]
Thanks @senja006 @woble , let's discuss here:
https://github.com/nosir/cleave.js/issues/147
