### ISSUE TITLE
Request: strict decimal places option

### ISSUE THREAD

**Issue by kouts** [nosir/cleave.js#108]
Hi great work on cleave! Is there any chance you could implement a strict decimal places option so that e.g 36500 would then always become 36.500,00 instead of 36.500

Thanks!

**Comment by nosir** [comment]
Hey @kouts, the one you proposed is a nice feature. But this is a bit too specific for masking numbers, I have to say this is not in the plan for now.
Thanks for supporting 👍

**Comment by nsecchi-carecloud** [comment]
Hi Nosir, quick question, has this request been addressed somewhere? I am also in need to format a number as a currency (2 should display as 2.00). If not, do you know if this was resolved in any of the forks? By the way, great work on the library!

Cheers!

**Comment by ReganRyanNZ** [comment]
Hi Nosir, just adding that I have this need too (maybe if enough people need it, you can consider adding this feature 😛)

If I load a number such as "9.10" it will appear in the cleave input as "$9.1" which looks a bit weird.

**Comment by efstathios** [comment]
I would say that we need this feature too :(

**Comment by Rambou** [comment]
We need that too!
