### ISSUE TITLE
Error with ES7 + React

### ISSUE THREAD

**Issue by nuthinking** [nosir/cleave.js#111]
Tried with Facebook react-create-app and I get:
`react.js:1 Uncaught SyntaxError: Unexpected token import`

**Comment by nosir** [comment]
Hey @nuthinking, can you please share your webpack config or wherever you refer cleave.js?

**Comment by nuthinking** [comment]
This one: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/config/webpack.config.dev.js

**Comment by nosir** [comment]
Had a look, the easiest way is to use bundled cleave file, in order to avoid ES future babel transpiler.

So in your App.js:

```
import React, { Component } from 'react';
import Cleave from 'cleave.js/dist/cleave-react.min';
import CleavePhone from 'cleave.js/dist/addons/cleave-phone.gb';

class App extends Component {
  render() {
    return (
      <div>
        <Cleave placeholder="Enter phone" options={{phone: true, phoneRegionCode: 'GB', noWarning: CleavePhone}}/>
      </div>
    );
  }
}

export default App;
```

**Comment by nosir** [comment]
@nuthinking Let me know if it works for you.

**Comment by chmanie** [comment]
First of all, thank you for putting together this great library!

I do, however, have the exact same error using Meteor. It'd be great if it just worked out of the box. I'll try to use the workaround for now!
