### ISSUE TITLE
Wrong model value updated in AngularJS when having multiple fields

### ISSUE THREAD

**Issue by markleusink** [nosir/cleave.js#113]
If you have multiple fields on a form and they all use the same cleave options object, the wrong model values are updated. See this fiddle: https://jsfiddle.net/markleusink/ve758jjt/

I looked at the directive and think I know what's going on, am working on a solution.

**Comment by markleusink** [comment]
Just submitted a fix for this issue. The problem was caused by the two-way binding of the `cleave` attribute in the directive: the `$scope.cleave` object was overwritten in the precompile function for every instance, causing the object in the parent scope (`options`) to be updated.  I fixed it by using a one-way object literal binding.

**Comment by nosir** [comment]
Thanks a lot @markleusink merged!
