### ISSUE TITLE
Add percentage support for numeral formatting

### ISSUE THREAD

**Issue by dfedynich** [nosir/cleave.js#115]
Hey, guys! Could you add percentage support for numeral formatting? It seems, that numeric formatting has all popular customization features like delimiter and decimal mark and even rarer styles like Indian and Chinese numbering group style. Awesome! I guess, that adding percentage support would rich the coverage of numeral formatting. The only thing, that I suggest is to make available to enter '%' sign at the end of a digit. What do you think? Or do you, guys, hold the opinion to leave the task of appending suffixes to developers?

**Comment by nosir** [comment]
As you said, I think this should be left to developers, to enter `%` or `‰` is a relatively high level behaviour, normally when you expect this to be done, I would rather put it as a label in the end out of th input field.

Thanks for proposing, will close this.
