### ISSUE TITLE
Add a Time formatter similar to the Date formatter

### ISSUE THREAD

**Issue by singerbj** [nosir/cleave.js#121]
I'm getting at the forced validation on the Date formatter (that doesn't allow you to put in 99 for a month).

24 hour time would be the most universal/easiest, but you could get fancy with 12 hour time and an AM/PM thing in the input.

**Comment by nosir** [comment]
Sorry for the delay @singerbj, we discussed about this, but decided not to add time format in cleave.js. Mostly because time input is a relatively rare requirement in general form.
Thanks for proposing this, will close.

**Comment by erisnuts** [comment]
+1 to this feature

**Comment by nosir** [comment]
Time supporting released, please check: #73 (comment)
