### ISSUE TITLE
numericOnly option doesn't work

### ISSUE THREAD

**Issue by AndrexGold** [nosir/cleave.js#122]
Hello, I have a problem with numericOnly option. 

From documentation about numericOnly option -> "A Boolean value indicates if it only allows numeric letters (0-9)."

When I set this option to "true", I should not type negative numbers, but I can do it.

For example, https://jsfiddle.net/ob8dvc48/2/.

**Comment by nosir** [comment]
Hmm, interesting. Didn't think about this, so you would like to use `numeral` type but limit users to enter negative number?

**Comment by AndrexGold** [comment]
Yes, I think, it will be cool.

For my project, I need to type only positive numbers. But I cannot do it with Cleave without extra actions. Is it possible to do any option for typing only positive numbers?

For example, 
`<Cleave options={{numeral: true, delimiter: "'", numeralThousandsGroupStyle: "thousand", onlyPositive: true} />`

**Comment by nosir** [comment]
Makes sense, will fix the option `numericOnly` to refuse `-`

**Comment by AndrexGold** [comment]
Thanks a lot for your work.

**Comment by nosir** [comment]
Published, added something in `numeral` type config, https://github.com/nosir/cleave.js/blob/master/doc/options.md#numeralpositiveonly

**Comment by iAyushAg** [comment]
Try using :
numeralPositiveOnly: true
