### ISSUE TITLE
Help in the way you broke out the various country validations

### ISSUE THREAD

**Issue by custa1200** [nosir/cleave.js#123]
Hi I would like to be able to write a server/client side validator where it uses libphonenumber like you have done and I have seen how you have each country broken out into individual libraries which is awesome to keep the size down. I would think it would be hard to do that each time the library is updated so have you got any pointers on how to just extract a single country like AU for example?

**Comment by nosir** [comment]
Have a look at this project https://github.com/leodido/i18n.phonenumbers.js
It fully supports libphonenumber features and inspired me a lot.

**Comment by custa1200** [comment]
Thanx mate, really appreciate the link and what you are doing with Cleave.
