### ISSUE TITLE
MasterCard is adding new BINs

### ISSUE THREAD

**Issue by ivyyangthl** [nosir/cleave.js#128]
From October 2016, MASTERCARD is adding a new 2-Series bin range 222100 – 272099 to be processed with and in the same manner as the existing bin range 510000 – 559999
https://www.linkedin.com/pulse/19-digit-visas-2-digit-mastercards-doug-smith

Can this be supported please? Thanks

**Comment by custa1200** [comment]
Pretty sure it already does.

**Comment by ivyyangthl** [comment]
Yes, I confirm it is there.
