### ISSUE TITLE
Support for React defaultValue

### ISSUE THREAD

**Issue by veksen** [nosir/cleave.js#131]
If I'm not mistaken, there seems to be no way to use defaultValue, like it is possible on an input.

**Comment by nosir** [comment]
Cleave doesn't support uncontrolled input components, which is defaultValue designed for.
To set a default value, you can pass `value="some_value"` in. The value should match the initial `state` value outside.

**Comment by nosir** [comment]
Doc updated:
https://github.com/nosir/cleave.js/blob/master/doc/reactjs-component-usage.md#how-to-pass-default-value
