### ISSUE TITLE
Add a min/max limit

### ISSUE THREAD

**Issue by madastro** [nosir/cleave.js#132]
Would it be possible to add a min/max limit to an input value? let's say for example, limit year to a specific range? TIA

**Comment by ducman** [comment]
+1 for numeric. I guess it can also be for dates.

**Comment by DimNS** [comment]
+1 for numeric

**Comment by christophemarois** [comment]
+1

**Comment by nosir** [comment]
Sorry for disappointing you guys. numeric is a good feature but a bit over what the lib was designed for.
Cheers, will close it for now.

**Comment by zek** [comment]
I know this issue closed and probably you still dont think to add this feature but please listen

@nosir this library is the one of the best library available.

Most of the libraries don't allow 8 decimals like 0.12345678. 

But in your library we got no floating limit. Only needed feature is minimum and maximum. If you can implement it that would be super cool.

Please inspect this ( https://kevinongko.github.io/vue-numeric/ ) This library provides min and max but decimal digit support and some other features doesn't work as expected.

**Comment by mseele** [comment]
@nosir any news here?

numeral min/max feature is the only thing that prevents us to move completely to cleave.js (We are using autonumeric for now).

We would love to move completely to cleave.js.

**Comment by AnnaVihrogonova** [comment]
Lack of numeral min/max feature is the only thing that disappointed me in Cleave.js. It will be super good if you guys could find a way to add it to the library.  Thanks!

**Comment by ReganRyanNZ** [comment]
+1 to request for max length of a number. I can hack the html input to have a maxlength but that's not as nice, as the commas/periods/prefixes are included in that..

**Comment by lesliev** [comment]
It's not ideal but you can use HTML5 form validations to prevent the submission of out-of-range values. Add data attributes data-cleave-min and data-cleave-max to the inputs you want to constrain and then do something like this:
(it uses jQuery but I'm sure you can adapt it if required)

```
function applyCleave() {
    $('[data-cleave-2dp]').each(function (index, e) {
      let el = $(e);
      let cleaveMin = el.data('cleave-min');
      let cleaveMax = el.data('cleave-max');
      let cleave = new Cleave(e, {
        numeral: true,
        numeralDecimalScale: 2,
        onValueChanged: function(ee) {
          if (cleaveMin || cleaveMax) {
            let val = parseFloat(ee.target.rawValue);
            if (cleaveMax != undefined && val != undefined && (val > cleaveMax)) {
              e.setCustomValidity('This value cannot be above ' + cleaveMax);
            } else if (cleaveMin != undefined && val != undefined && (val < cleaveMin)) {
              e.setCustomValidity('This value cannot be below ' + cleaveMin);
            } else {
              e.setCustomValidity('');
            }
          }
        }
      });
    });
  }
```

**Comment by edenizk** [comment]
My workaround for max value is `blocks: [Your limit]` and for `delimiter: ""`
