### ISSUE TITLE
Defining global cleave formatters when the selector may or may not exist

### ISSUE THREAD

**Issue by asanger** [nosir/cleave.js#134]
I'd like to define a set of cleave formatters that will always look for certain selectors and format them as necessary. I originally thought that I could simply instantiate them one after another, and if one of the selectors didn't find a match, it would just move on gracefully. Instead, cleave would error out with `Uncaught Error: [cleave.js] Please check the element` and then would not process anything else.

Is there a reason why Cleave does a hard fail when a selector is not found? If so, I will just have to wrap my cleave functions in something to check for the selectors myself. Otherwise, is it worth submitting a PR to look for the selector and move on gracefully if not found?

**Comment by nosir** [comment]
I think in general use cases, we try to prevent user introducing referring errors at the beginning. So for now we will stick to the current way, a hard fail will be thrown.
Thanks for proposing, will close this.
