### ISSUE TITLE
Numeric delimiters function inconsistently

### ISSUE THREAD

**Issue by harjup** [nosir/cleave.js#136]
I would like to use this library to format input for customer account numbers. Account number formats are specified externally, and can potentially be anything. 

For example, this could be a valid account number, where values wrapped in []s are delimiters:

`ABC[9]DEF[8]GHI[7]JKL`

Using the numbers 0-7 as delimiters cause cleave to replace all inputs after the delimiter with the delimiter character, so if I were to attempt to input the account number above, it would look like this in the input box:

`ABC9DEF8GHI7777`

As bizarre as it is to use numbers as delimiters, it would be nice to have this functionality be supported.

Fiddle Reproducing issue:
https://jsfiddle.net/srjv9cua/5/

**Comment by nosir** [comment]
Sorry for the delay, fixed @v0.7.23
Your fiddle demo should work fine now.
