### ISSUE TITLE
From cdnjs, about library request.

### ISSUE THREAD

**Issue by Piicksarn** [nosir/cleave.js#139]
Hi @nosir  ~
This is  **[cdnjs](https://github.com/cdnjs/cdnjs)**.
There is a lib request :point_right: https://github.com/cdnjs/cdnjs/issues/9631 , and we desire to contain **cleave.js.**:smiley: 
However, I must to make a check for the files that we need to added.

The files I would like to add are : **all the files under dist folder.**

Is that complete for the user? Or other files required?

Thanks for your great work ✨

Piicksarn

**Comment by Voziv** [comment]
Yep! Only the dist folder is needed to run cleave.js

**Comment by nosir** [comment]
Sorry for the late guys, still in vacation.
Yes, only the dist folder is complete for the user.
Thanks
