### ISSUE TITLE
Editing does not work correctly. Jumps to the end.

### ISSUE THREAD

**Issue by swernerx** [nosir/cleave.js#142]
When editing some value in-between e.g. the just the day of a date, the input directly jumps to the end after editing. I figure this behavior is not what the user assumes should happen. The cursor should always move naturally to the next position when editing and not to the end.

**Comment by gustavopch** [comment]
A fix to this is soooo important.

**Comment by nosir** [comment]
Sorry, don't think this will be solved in the near future. Duplicated with this: https://github.com/nosir/cleave.js/issues/25
