### ISSUE TITLE
Date Formatter : Switch to next part and add 0 when delimiter is typed

### ISSUE THREAD

**Issue by remicoges** [nosir/cleave.js#145]
Hello !

When typing a date, if the delimiter is typed following a digit, ie: 1/, the formatter should add the 0 before the digit and switch to the month.

Following this pattern, 1/ 1/ 2017 should return 01/01/2017 as many people don't type the 0 when entering a date 

Could you add this to this nice project ?

Thanks

**Comment by nosir** [comment]
Thanks for the suggestion.
However the point of this lib is to prevent use typing delimiter, and this behaviour should work consistently for all input type.
Will close this for now.
