### ISSUE TITLE
React: Numeral with comma as decimalMark break when also having value set 

### ISSUE THREAD

**Issue by mikkelwf** [nosir/cleave.js#148]
I've setup a Cleave to be used with the numeral option.

However when using comma as decimal, it's impossible to set the value with any decimal value. It's simply chopped of.

It works when you omit the `value` props.

WIth dot as decimal it works as expected. 

Fiddle of the error:
https://jsfiddle.net/mikkelwf/ym61hjyu/4/

**Comment by nosir** [comment]
I think this problem is you bind Cleave value attribute with the state, which causes the problem.
Check this fixed fiddle: https://jsfiddle.net/nosir/gk32jbs5/
value could be only used to pass the initial default value, please see the comment here:
https://github.com/nosir/cleave.js/issues/129#issuecomment-272149093

**Comment by mikkelwf** [comment]
I must admit i still see this as a bug - or at least very unexpected behaviour. 

So the `value` is actually `initialValue`, and you cannot update the value with `value` after initialization, otherwise the component (might) break.

So this is the two options (bugs) as i see it:
* _`value` works as `initialValue`._ 
**Bug:** The component lets the user set `value` after initialization, which leads to unexpected behaviour.
* _`value` works as expected (here meaning that it allows for setting the value at any point)._ 
**Bug:** See my original fiddle.

You say in #129 that it's not needed to set value, but it's really not clear how value works, and that's a problem. The general expectation for a react input component is that value allows for updating the value of the component at any point.

**Comment by nosir** [comment]
Yes, to bind `value` to any state can lead to unexpected behaviours, I added some doc regarding to the `value`, hope this helps:
https://github.com/nosir/cleave.js/blob/master/doc/reactjs-component-usage.md#how-to-pass-default-value
and 
https://github.com/nosir/cleave.js/blob/master/doc/reactjs-component-usage.md#how-to-update-raw-value

**Comment by carlos-mora** [comment]
Reactivity depends on the update of the state. For example it can be useful to change some attributes depending on the current value, or mark a value with special colors when it's value is not valid.
