### ISSUE TITLE
OnChange event not being fired on Google chrome

### ISSUE THREAD

**Issue by jlariza** [nosir/cleave.js#151]
Hi,

I am using a numeral Cleave and adding some functionality when the field has changed. The problem is that on google chrome, the change event does not always get fired. On Mozilla Firefox it does get fired but not on chrome. I think it may be related with issue #58.

I fixed it using a keyup event but the change event should be fired.

Thank you

**Comment by nosir** [comment]
Yea, same issue as https://github.com/nosir/cleave.js/issues/58
Will close this one and track it there.
Thanks 👍
