### ISSUE TITLE
Cleave Int input

### ISSUE THREAD

**Issue by mrozado** [nosir/cleave.js#152]
Hi, is there a way of making Cleave use integers only? 

No delimiter or decimals

**Comment by tiagomatosweb** [comment]
I came across with this

```
new Cleave('.int', {
                numeral: true,
                numeralDecimalMark: '',
                delimiter: '',
            });
```

But I'd like to know how to delimiter with just 2 character.

**Comment by tiagomatosweb** [comment]
That is actually simple

```
new Cleave('.int', {
   blocks: [2],
   numericOnly: true,
});
```

In your case would be something like
```
new Cleave('.int', {
  numeral: true,
  numeralDecimalMark: '',
  delimiter: '',
});
```

**Comment by nosir** [comment]
Yea, exactly, just as @tiagomatosweb posted, pass empty string to `numeralDecimalMark` and `delimiter `.
Will close this for now, thanks for playing with it.

**Comment by xyzzyxyzzy0077** [comment]
What does the trick is actually `numeralDecimalScale: 0` to not allow decimal inputs
