### ISSUE TITLE
React-version has side-effect in IE11

### ISSUE THREAD

**Issue by cantorio** [nosir/cleave.js#154]
Hi!
I run 2 demos from official demo-page (react and basic version) in IE11:
https://jsfiddle.net/nosir/gLLsrxxf/
https://jsfiddle.net/nosir/kbaxx64s/

they have different behavior: in react-version (only in IE11) if I enter some illegal charater into input (for example, any letter in "number"-input), that charater actually appears inside input and after some very short time it's being deleted (like i pressed backspace).
In basic version everything works just fine.
This "flashing" is very annoying and it would be great to fix this issue to be able to use this library in production.
Thanks.

**Comment by nosir** [comment]
Thanks for reporting.
Will check what's going on with it soon.

**Comment by nosir** [comment]
@cantorio Sorry for the delay
I've updated react.js to 15.6.2 in the jsfiddle, and seems this problem is solved in IE11.

**Comment by nosir** [comment]
Closing this, let me know if you have any further issue
