### ISSUE TITLE
No support for input types other than text

### ISSUE THREAD

**Issue by jansokoly** [nosir/cleave.js#158]
Cleave works very well with `<input type="text">`, but does not work with `<input type="number">` and possibly other input types.
For example, using following formatter with `type="number"` only allows the user to type 3 digits. After typing the third one, everything is removed.
```
var cleave = new Cleave('.input-element', {
    numeral: true,  
    numeralThousandsGroupStyle: 'thousand'  
});
````

**Comment by andys8** [comment]
All of those libraries struggle with input type `number` and it seems to be due to browser API limitations.

**Comment by nosir** [comment]
Yea, cleave assumes you are using `text` as the input type. All in all, it handles strings and does all the formatting stuff.
Thanks, will close this.

**Comment by jansokoly** [comment]
Sure, but focusing such a field on a smartphone opens alphabet keyboard instead of numeric one. Just to explain why it matters.

**Comment by nosir** [comment]
Oh, so if this is only you need, you can set it to `<input type="tel">`, this should trigger number keyboard on mobile also works well with cleave.js.

**Comment by dastiw1** [comment]
with jquery migrate `<input type="tel">` not works

**Comment by kennycrosby** [comment]
@jansokoly were you able to get this to work??

**Comment by kennycrosby** [comment]
@nosir is there any way to do that with react syntax? I want to be able to pull up the number keyboard on mobile.

`<Cleave className='width-60'
                    tabIndex="6"
                    name='user.phoneNumber'
                    placeholder="Mobile Phone Number"
                    options={{
                      numericOnly: true,
                      delimiters: ['-', '-'],
                      blocks: [3, 3, 4],
                    }}
                    onChange={this.handleInputChange.bind(this)}
            />`

**Comment by nosir** [comment]
@kennycrosby cool, please track the request here: https://github.com/nosir/cleave.js/issues/217

**Comment by kennycrosby** [comment]
@nosir okay thanks!

**Comment by natedunn** [comment]
How is using `tel` or `text` for everything a semantic and appropriate option?

**Comment by graham-saunders** [comment]
Seeing support for number and other HTML 5 input types would be great

**Comment by boyanenchev1** [comment]
@nosir 
I want to enter UK Ni number which is combination of letters and digits but 
after entering of 2 digits in a row the keyboard shifts to alphabet instead of staying on number ones.
I have this issue only on Android.
Any suggestion? Thanks

**Comment by robbienohra** [comment]
why was this closed?
