### ISSUE TITLE
Month Autocomplete

### ISSUE THREAD

**Issue by blazedd** [nosir/cleave.js#16]
I just found your project, so I haven't had time to dive into contributing just yet. I'd like to make a feature request specific to any entries which directly affect date **month** attributes.

If the user types anything larger than a "1" it should automatically prefix it with a zero. Just from a UX perspective, when are they ever going to type any month larger than 12?

Few examples

"2" -> "02"
"1" -> "1" (no change)
"6" -> "06"
"12" -> "12" (no change)

**Comment by nosir** [comment]
Yes, that's a good point. It could also apply to **day** attributes.

"4" -> "04"
"3" -> "3" (no change)

**Comment by nosir** [comment]
FYI, I'm on it.

**Comment by nosir** [comment]
Published, thanks guys.
