### ISSUE TITLE
Padding credit card numbers with spaces should depend on the cursor's direction of travel

### ISSUE THREAD

**Issue by skington** [nosir/cleave.js#160]
Related to [the other thorny issue of credit card number formatting](https://github.com/nosir/cleave.js/issues/25) but simpler: a space at the end of a credit card number (PAN) should only appear if the user is adding digits to the PAN. If they are deleting digits, any final padding space between two groups of digits should be removed as soon as the last digit of the right-most group is removed.

Currently, if you type `4444` a space is automatically inserted, so the cursor is after `4444␠` ready for you to carry on entering e.g. `4444␠33...`. Once you enter the full PAN e.g. `4444␠3333␠2222␠1111`, no further spaces are added. These are both good things and correct behaviour.

However, if you delete the final `1111`, the cursor stays after the space at the end of the PAN: `4444␠3333␠2222␠`. The code should recognise that the PAN is being truncated, and should get rid of the final space so the cursor ends up immediately to the right of `2222`, ready to delete those digits in turn.

**Comment by nosir** [comment]
Thanks @skington Your description is really nice and detailed 👍
Cursor and backspace is always annoying, we will have a look.

**Comment by nosir** [comment]
So, the cursor problem... after all the evaluation and tests, we considered it as a feature missing by design from the beginning and decided not to apply any hacky fix for it for now.

We also see this as a major flaw with `cleave`, will try to solve it when rewriting the lib.

Thanks
