### ISSUE TITLE
Uncaught TypeError: Cannot set property 'initValue' of undefined

### ISSUE THREAD

**Issue by edge0703** [nosir/cleave.js#164]
No matter what I do, I always get this error. I already stripped the page down to an <input> element and just the call of the script, but still get this error. Also happens in the unminified script.

**Comment by edge0703** [comment]
Alright, it seems that `var cleave = new Cleave('#ccnumber')` alone doesn't work, didn't realize that you also need to specify the type of field.
```
var cleave = new Cleave('#ccnumber', {
   creditCard: true
});
```

**Comment by nosir** [comment]
Yea, it requires you define the options to make it work.
Will update the doc.
Cheers.
