### ISSUE TITLE
Option to keep delimiter values in model output

### ISSUE THREAD

**Issue by calculatedstallion** [nosir/cleave.js#165]
So currently the delimiters seem to get stripped out of the model output.
https://jsfiddle.net/v3aLq6x6/1/

Is it possible to keep them in the model output? Or ideally have an option to set them to be retained?

**Comment by nosir** [comment]
https://jsfiddle.net/nosir/5ysgqrpc/

I guess this is what you need?
Will close this, feel free to open if you still have problem.
