### ISSUE TITLE
phone number prepend country code

### ISSUE THREAD

**Issue by olpoco** [nosir/cleave.js#168]
How to prepend country code to phone number returned in onChange, for example, add +1 for US?

**Comment by aconital** [comment]
I would like to know aswell! Also how can I add the dropdown options in react for phone input?

**Comment by nosir** [comment]
I don't think this is related to the lib itself, but I created a demo and added to the example jsfiddle:
https://jsfiddle.net/nosir/0amruddk/

**Comment by eleumas** [comment]
Hi! I tried to copy the code in your demo https://jsfiddle.net/nosir/0amruddk/ but doesn't work. 
I use the latest versione of cleave.js and jquery 3.3.1.
