### ISSUE TITLE
Auto Format Pasted Text

### ISSUE THREAD

**Issue by adfie** [nosir/cleave.js#170]
Hello?
thanks for creating really helpfull library...
And it would be more nice if it can automatically format pasted text like, ie if i pasted 2.777.333 
it would turn to 2,777,333 

thanks....

**Comment by nosir** [comment]
Yes. Glad you liked the lib.
Basically, to achieve your request, it requires user to define the delimiter to be replaced as well, this is a bit complicated in usage.
Still thanks for supporting, will close this.
