### ISSUE TITLE
How I can handle zip and zip+4 codes?

### ISSUE THREAD

**Issue by zetoke** [nosir/cleave.js#172]
Hello!
Thanks for a great lib!

I have 1 input for `zip (11111)` or `zip+4 (11111-1111)` codes.
How I can prevent adding `-` to the input if I use `blocks: [4, 4]` and `delimiter: '-'` and writing `12345` to the input?

**Comment by nosir** [comment]
Hi, guess you mean use blocks: `[5, 4]`?
Basically cleave append the delimiter before the next character appears, so I'm afraid it can't be done with the lib.
Thanks for the love :)
