### ISSUE TITLE
raw value is not set by default

### ISSUE THREAD

**Issue by alwex** [nosir/cleave.js#173]
Hello and thank you for this nice library!

I am using Cleave with React + Flux, and I have notice something very annoying.
`event.target.rawValue` is not setted by default while handling events.
eg:

```
handleBlur(event) {
    console.log(event.target.value) // output hello
    console.log(event.target.rawValue) // output undefined
}
<Cleave onBlur={this.handleBlur} value="hello" />
```

in case the user just focus then leave the field, `event.target.rawValue` is undefined, it lead to unexpected behaviour while trying to react on field blur.

**Comment by nosir** [comment]
@alwex Sorry for the delay, fixed in https://github.com/nosir/cleave.js/releases/tag/v0.8.0
Demo: https://jsfiddle.net/nosir/jt0706bg/
