### ISSUE TITLE
Cleave.js not working, give error => Uncaught Error: [cleave.js] Please check the element

### ISSUE THREAD

**Issue by Jahleel17** [nosir/cleave.js#174]
# Hello cleave community and # support.
I downloaded the cleave.js-master from github, and included the cleave.min.js from cleave.js/dist/cleave.min.js , but My input is not getting formated.
in my console I am having an error 
<<
Uncaught Error: [cleave.js] Please check the element
>>
what is the cause and how can I solve this?

**Comment by jpcaparas** [comment]
I'm assuming you're calling `Cleave` before the element has loaded, which is why it's throwing that error. 

Use it like this:

```
document.addEventListener('DOMContentLoaded', () => {
    const cleave = new Cleave(fieldSelector, {
        phone: true,
        phoneRegionCode: phoneRegionCode
    });
});
```

**Comment by nosir** [comment]
Thanks @jpcaparas 
Exactly, you need to get input element ready in your dom first

**Comment by leoncio77** [comment]
nosir, para usar cleave.js es necesario instalar el node.js, y luego correr npm value.js

ahora estoy trabajando con xampp, pero no me esta funcionando las entradas de los formatos, ya tengo los dos <script src= value.min.js>  y aun no me funciona el input, no me formatea el valor en mi navegador..
por favor ayudame, dime que debo hacer??

**Comment by danabstude** [comment]
@nosir  
 Output : Cleave is not a constructor
`<script src="cleave.js"></script>
        <script src="cleave-phone.i18n.js"></script>
        <script src="jquery-3.6.0.js"></script>
        <script>
            document.addEventListener('DOMContentLoaded', () => {
    const cleave = new Cleave('#phnnumIput', {
        phone: true,
        phoneRegionCode: 'US'
    });
});
        </script>`
