### ISSUE TITLE
May I change options on the fly?

### ISSUE THREAD

**Issue by iserdmi** [nosir/cleave.js#176]
I do something like this:
```
const cleave = new Cleave('.my-selector', {
  numericOnly: true,
  blocks: [3, 2, 3]
});
```
Then I need change `blocks` option for this element, for example (pseudo code):
```
cleave.setOptions({
  blocks: [4, 4]
});
```
How can I do this? Right now I need destroy cleave and create it again.
```
let cleave = new Cleave('.my-selector', {
  numericOnly: true,
  blocks: [3, 2, 3]
});
cleave.destroy();
cleave = new Cleave('.my-selector', {
  numericOnly: true,
  blocks: [4, 4]
});
```

 Or am I do something wrong?

**Comment by nosir** [comment]
Hi @iserdmi 
Unfortunately the lib doesn't provide any `setOptions` api on the fly, you are absolutely doing it correctly.
Destroy it first and create a new one is the right way.
Thanks
