### ISSUE TITLE
Can't create prefixed-only input

### ISSUE THREAD

**Issue by alterx** [nosir/cleave.js#18]
It looks like removing the `blocks` option effectively breaks the ability to create a prefixed input. Is this an expected behavior?

One would think that creating prefixed inputs shouldn't be affected by the lack of the `blocks` property as there are many use cases in which you'd just want a prefixed field.

Here's a jsfiddle in which you can replicate the issue
https://jsfiddle.net/6od8hLp0/

I'll start looking into the code to see if this is an easy fix but I just wanted to log this in case this was an expected behavior or something intended to be that way.

**Comment by alterx** [comment]
Added PR to fix this issue #20

**Comment by nosir** [comment]
Hi @alterx, thanks for looking into the code and sending the PR. Agree with you, this is something should be provided. Will test it a bit and merge after work.
