### ISSUE TITLE
What about 19 digit cards?

### ISSUE THREAD

**Issue by gabrielmicko** [nosir/cleave.js#181]

**Comment by gabrielmicko** [comment]
In the meantime I found this option:
`
'creditCardStrictMode': true,
`
According to this [WIKI page](https://en.wikipedia.org/wiki/Payment_card_number), the length of the credit card numbers can be 19 in more then one case (not just VISA).

**Comment by nosir** [comment]
Thanks @gabrielmicko, merged!
