### ISSUE TITLE
React 15.5 Deprecation Warning

### ISSUE THREAD

**Issue by ztanner** [nosir/cleave.js#183]
`React.createClass` is being deprecated in v16, so those who are using Cleave will be presented with the following warning:

> Warning: Cleave: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement

**Comment by nosir** [comment]
Thanks @ztanner merged 👍
