### ISSUE TITLE
Limit Phone number formatting to 10 digits

### ISSUE THREAD

**Issue by shaz13** [nosir/cleave.js#185]
![screenshot from 2017-05-08 10-50-10](https://cloud.githubusercontent.com/assets/24438869/25791171/2de621b8-33dc-11e7-8fa0-22ac51623531.png)
The rest of the fomarting has limit of input, example for credit card, date etc. As phone numbers are strictly 10 digits with +2 digits of country code, it must be limited

**Comment by nosir** [comment]
It applies the formatting and limitation only when the input number is a valid number of that country.
In your case, `FJ` has country code `+679`, a valid number will be `+6798812345` or `8812345`
