### ISSUE TITLE
Date value should be returning in standard yyyy-mm-dd ISO format

### ISSUE THREAD

**Issue by Andriy-Kulak** [nosir/cleave.js#186]
Hi So I am using Cleave js react version for date input fields (component below).

The standard US way date format is "mm/dd/yyyy" which is what I have currently. However, as I get the value of the input, it should come back in the standard[ ISO format](https://en.wikipedia.org/wiki/ISO_8601) of 'yyyy-mm-dd' instead of regular value 'mm/dd/yyyy' or rawValue 'yyyymmdd'.

How can i achieve this without splicing/concat the date string? It seems like that would be an overkill and will potentially cause trouble if I try to set initial values.

The reason I ask is Moment.js is giving a warning when i give it the value of mm/dd/yyyy:
> Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release.

```
<Cleave className="input-numeral"
                      id={this.props.data.name}
                      value={this.state.value}
                      placeholder="mm/dd/yyyy"
                      options={
                        {
                          date: true,
                          datePattern: ['m', 'd', 'Y']  
                        }}
                      onChange={this.handleChange}/>;
```

**Comment by nosir** [comment]
Added an method: https://github.com/nosir/cleave.js/blob/master/doc/public-methods.md#getisoformatdate
But in react case, you will need to follow this: https://github.com/nosir/cleave.js/blob/master/doc/reactjs-component-usage.md#how-to-update-raw-value
demo: https://jsfiddle.net/nosir/67ez0tf6/
