### ISSUE TITLE
Different format for input view and output model/backend

### ISSUE THREAD

**Issue by pcollaog** [nosir/cleave.js#188]
How can I format the view with this pattern 'd-m-Y' (angular) and receive in the model ISO format ('Y-mm-dd') to call the backend? in this case the view is not the same as I use in the model or backend. 

Any idea? maybe in date or other element needs format to the view and format to the output, it would be nice.

Good work!

**Comment by nosir** [comment]
Added a method: https://github.com/nosir/cleave.js/blob/master/doc/public-methods.md#getisoformatdate

Then you need this: https://github.com/nosir/cleave.js/blob/master/doc/angularjs-directive-usage.md#how-to-call-public-methods

demo: https://jsfiddle.net/nosir/frtfwop5/

**Comment by nosir** [comment]
Closing this, hope the solution fits your need.
