### ISSUE TITLE
Support suffix option

### ISSUE THREAD

**Issue by adcosta118** [nosir/cleave.js#189]
Since there is a `prefix` option wouldn't it make sense to support a `suffix` or `unit` option too?

A simple use case would be € currency, where the symbol comes after the value.

**Comment by nosir** [comment]
Hi, unfortunately suffix support is not in the plan due to the annoying cursor jumping issue.
We will look to solve this in the next version.
Thanks.

**Comment by benface** [comment]
What is this "next version" you're referring to here? I'm very interested in a suffix option as well.

**Comment by alxndr-w** [comment]
> Hi, unfortunately suffix support is not in the plan due to the annoying cursor jumping issue.

What kind of cursor jumping issue?

**Comment by alxndr-w** [comment]
I always came back to this issue while searching for a solution. We managed to get a great result:

![2020-11-10 16-54-19_Trim_1](https://user-images.githubusercontent.com/3855487/98796930-3e65d280-240c-11eb-97ee-62f9e429dfef.gif)

1. The input value gets copied to a hidden/transparent span element with the same font formatting settings (size, family...)
2. We measure the width of the span element and calculate the padding needed to center the input value as well as the unit element
3. We update the padding on every value change.

I guess this solution will not find its way into cleave.js but it might be a nice workaround for those who need it.
