### ISSUE TITLE
Add support to regex so users will be able to alter behavior without dig to source code

### ISSUE THREAD

**Issue by anatoly314** [nosir/cleave.js#19]
From our discussion at Reddit, just add support to Regex so user will be able to add custom behavior via regex without need to change source code of your component.

**Comment by nosir** [comment]
@anatoly314 Thanks for the advice. This could be more handy for advanced users. Will evaluate and test it.

**Comment by trjiang** [comment]
Sorry for letting you guys down, we've decided not to add anything related to regex.

The idea of the lib is to be as basic and simple as possible, to offer the regex option will make user potentially touch it and stuck on using the whole thing.

For me, to write proper regex is never an easy thing, I'd prefer not to provide it here.

Thanks guys again, @nosir please close.

**Comment by mikesaintsg** [comment]
> From our discussion at Reddit, just add support to Regex so user will be able to add custom behavior via regex without need to change source code of your component.

Here is something I've come up with as a quick fix for alphanumeric input, it's reactive to the input, so not as clean as when you use numericOnly with Cleavejs, but it does the trick if you want to use custom regex that validates as the user types. 

            $('#id').on('keyup', function () {
                var input = $(this).val();
                var regex = input.replace(/[^\w]/g, "");
                $(this).val(regex);
            })
