### ISSUE TITLE
Cleave phone + webpack in vue.js

### ISSUE THREAD

**Issue by hedaro** [nosir/cleave.js#190]
Hi, i am working in a project made with vue.js, and i am using cleave.js in some components.
It was working good, until a couple of weeks ago when we decided to use webpack to build the project. We noticed that our phone input component wasn't working anymore and it throws an error.

In my component I require it like this (we are also using babel):
```
import Cleave from 'cleave.js'
require('cleave.js/dist/addons/cleave-phone.mx');
```
And then create a new instance like this:
```
this.cleave = new Cleave(this.$el, {
        phone: true,
        phoneRegionCode: 'MX'
});
```

The error i get is: 
`Error: [cleave.js] Please include phone-type-formatter.{country}.js lib`

**Comment by nosir** [comment]
@hedaro would you be able to create a jsfiddle demo? Thanks.

**Comment by leoelcoder** [comment]
@hedaro Verify if you're not importing the `cleave.js` in other component,
I think this issue is cause by importing twice the `cleave.js` and you're
overrinding a reference `Cleave` that already has the lib `cleave.js/dist/addons/cleave-phone.mx` with a new one that has not that lib

as you can see here:

```
try {
    pps.phoneFormatter = new Cleave.PhoneFormatter(
        new pps.root.Cleave.AsYouTypeFormatter(pps.phoneRegionCode),
        pps.delimiter
    );
} catch (ex) {
    throw new Error('[cleave.js] Please include phone-type-formatter.{country}.js lib');
}
```

that exception has reached because `Cleave` has not `AsYouTypeFormatter` function. I mean has  no cleave.js/dist/addons/cleave-phone.mx lib

**Comment by hedaro** [comment]
@nosir Sorry for not answering before, i was moved to other tasks and left this issue pending.

I think the problem is what @leoelcoder mentions. I had two different components that both imported celave. We have refactored them into a single component that changes behavior based on props and it seems to be working without issues.

**Comment by nosir** [comment]
Good to know, thanks @leoelcoder

**Comment by patriciabobes** [comment]
Hi! It doesn't works for me. Kind of a different scenario though. 
- Typescript React app 
- yarn add cleave.js @types/cleave.js
If it works in your end, could you please share the code? Thanks!

**Comment by aarongerig** [comment]
Hi @patriciabobes,
This worked for me:

```
export default function phoneFormatter() {
  const field = document.getElementById('#phone-number');

  if (field) {
    Promise.all([
      import(/* webpackChunkName: 'cleave' */ 'cleave.js/dist/cleave.min'),
      import(/* webpackChunkName: 'cleave-phone-ch' */ 'cleave.js/dist/addons/cleave-phone.ch'),
    ]).then(([{ default: Cleave }]) => {
      const formatter = new Cleave(field, { phone: true, phoneRegionCode: 'CH' });
      formatter.init(); // This is only so ESLint is happy -> no-new/no-unused-vars conflict
    });
  }
}
```
