### ISSUE TITLE
How does cleave works?

### ISSUE THREAD

**Issue by DevGrohl** [nosir/cleave.js#192]
I would like to know how Cleave.js stops the propagation of some punctuation characters like quotes, double-quotes and apostrophes. 

I think it has something to do with propagation in the browser or OS but i cant find a way to disable this feature.

**Comment by nosir** [comment]
It strips all the non-numeric characters when `input` event is triggered:
Check here:
https://github.com/nosir/cleave.js/blob/017c734a25d5e5941ee5859aaaa5e5360da2a588/src/Cleave.js#L212
