### ISSUE TITLE
Credit Card Input: Cursor is set to end of input while editing something in the middle

### ISSUE THREAD

**Issue by nikolodien** [nosir/cleave.js#193]
Suppose you have the following input,

2423 2342 323**4** 2432

Now, if you try to delete **4**, it will put the cursor to the end of the input. The same thing occurs when you try to add a number in the middle. One of the reasons credit card input is mimicked to show the spaces on physical card is to enable users to identify errors easily. But if users are not able to edit the number easily, then the feature is not that useful.

**Comment by nosir** [comment]
Yea, the cursor problem has been discussed a lot, but after all the evaluation and tests, we considered it as a feature missing by design from the beginning and decided not to apply any fix for it.

We also see this as a major flaw with `cleave`, will try to solve it when rewriting the lib.

Thanks

**Comment by SashaDesigN** [comment]
I had same issue on React with any type of text inputs, it related to React itself and it behavior
