### ISSUE TITLE
Cursor moves to end when typing in between number

### ISSUE THREAD

**Issue by anoop-ananthan** [nosir/cleave.js#198]
Suppose you have already a number value in the currency textbox say `123,456.00` and you want to put two zeros between `4` and `5`, as you type first zero, the cursor goes to the end of the number there by making data entry difficult.

**Comment by nosir** [comment]
Yea, this is an annoying issue has been discussed.
Unfortunately, too much effort for this, so there is no plan to fix it until we found a really good way to handle the input events.
Thanks
