### ISSUE TITLE
country codes: 'us' works, 'ca' doesn't

### ISSUE THREAD

**Issue by phil-evans** [nosir/cleave.js#200]
i'm having functionality issues with the canadian region code..

- if i include 'addons/cleave-phone.**us**.js' and set 'phoneRegionCode: '**us**' - it works
- if i include 'addons/cleave-phone.**ca**.js' and set 'phoneRegionCode: '**ca**' - it doesn't work

by 'doesn't work' i mean the plugin doesn't seem to fire at all on the input.

any ideas? thanks

**Comment by nosir** [comment]
Thanks for reporting. Fixed @v0.7.22
