### ISSUE TITLE
Clarify `numeralIntegerScale`

### ISSUE THREAD

**Issue by adnasa** [nosir/cleave.js#204]
Hey @nosir,
thanks for this project.

---

You ought to clarify what `numeralIntegerScale` entails in the docs, would have especially helpful if your [releases](https://github.com/nosir/cleave.js/releases/tag/v0.7.21) included a breaking change section

In one project, we found out that this has affected all numerical values (including inputs which represented a money value such as a price of a product) of our app, where the value exceeded the length of `10` (default value to `numeralIntegerScale`)

ref: https://github.com/nosir/cleave.js/issues/196

**Comment by nosir** [comment]
Hey, do you mean this? https://github.com/nosir/cleave.js/blob/master/doc/options.md#numeralintegerscale

But I agree, `10` is not an ideal default value, it should have been designed in a better way.

**Comment by adnasa** [comment]
yes, that is the option I was referring to.

possible solution:
either that, or you have it disabled when no value is given upon mount.

**Comment by tdeekens** [comment]
I would disable defaulting to any numeral integer scale as it might confuse people. Whenever they opt into it, it's an explicit choice.

**Comment by adnasa** [comment]
strictly speaking no default value is ideal.

**Comment by nosir** [comment]
Okay, will fix.

**Comment by adnasa** [comment]
with the upcoming fix, will it be compatible with `numeralIntegerScale: 0`?
atm we set `numeralIntegerScale` to `0` to disable it

**Comment by nosir** [comment]
Yes, either `0` or no value is given will disable the integer scale, so it will be fine in your case.

**Comment by adnasa** [comment]
perfect, @nosir 👌🏽
I like this.
looking forward to your update, please keep me in the loop

**Comment by nosir** [comment]
Hi guys, fix released:
https://github.com/nosir/cleave.js/releases/tag/v0.9.0
Cheers

**Comment by tdeekens** [comment]
Thanks a lot!

**Comment by adnasa** [comment]
thanks @nosir 👌🏾
