### ISSUE TITLE
Leap year validation date input

### ISSUE THREAD

**Issue by pleongomez** [nosir/cleave.js#205]
Hi @nosir, 

Is there any way to avoid to type an incorrect date? For example: 2017/02/29. 

2017 is not a leap year, so there is no february 29.

Thanks!!
Regards.

**Comment by nosir** [comment]
HI @pleongomez thanks for the suggestion.
Actually it's not applying strict validation currently, so you can even enter 02/31/xxxx :p
Let me have a look.

**Comment by nosir** [comment]
Fixed and released in https://github.com/nosir/cleave.js/releases/tag/v0.9.2

**Comment by pleongomez** [comment]
Hi @nosir,

Thanks you a lot, I'm going to apply it to my project.

Excellent work!
Regards.
