### ISSUE TITLE
Cleave interfering with Chrome date / time picker

### ISSUE THREAD

**Issue by gniknosmirceht** [nosir/cleave.js#206]
I'm primarily using Cleave as a backup for browsers that don't support input type = "date" and "time" pickers. However, when I pick a date in Chrome, it is instantly reset to the default "mm/dd/yyyy" display. I tried moving the Cleave code to the end of the page and removing the event listener, but that doesn't change anything. Thanks for reading/any help you can provide!

**Comment by nosir** [comment]
Hi, I would suggest you generate your modernizr js to test if input type date is supported:

1. https://modernizr.com/download?setclasses search `form input types` build that feature
2. So include this before cleave.js: `<script src="js/modernizr.js"></script>`
3. Then do:
```
if (!Modernizr.inputtypes.date) {
    // do your fallback to setup cleave.js
}
```

**Comment by joshwhiplash** [comment]
Thank you for the help—I didn't check in, but I appreciate it and this looks like the correct response.
