### ISSUE TITLE
Can't use Cleave phone with React

### ISSUE THREAD

**Issue by omrihq** [nosir/cleave.js#207]
Trying to use Cleave phone with react, but getting an 
`Please include phone-type-formatter.{country}.js lib` error, and I'd like to use all country codes. How would I format my imports accordingly?

**Comment by nosir** [comment]
import CleavePhone from 'cleave.js/dist/addons/cleave-phone.i18n';

**Comment by nosir** [comment]
See more:
https://github.com/nosir/cleave.js/blob/master/doc/reactjs-component-usage.md
https://github.com/nosir/cleave.js/blob/master/doc/phone-lib-addon.md#how-to-include-phone-lib-addon
