### ISSUE TITLE
onInit is not fired when cleave.js is without any options

### ISSUE THREAD

**Issue by Tommy10802** [nosir/cleave.js#208]
Hello, thanks for your great plugin.

I started to use it for my project as global input component. 
I have one little problem. When I render cleave input for general text input without any cleave options,
e.g.
`
onInputInit = (cleave) => {
    cleave.setRawValue(this.props.initialValue)
}
`
`
<Cleave
        onChange={this.onInputChange}
         onInit={this.onInputInit}
/>
`
onInit is not fired up and initial value is not set.
I think it is because of this line
`
 if (!pps.numeral && !pps.phone && !pps.creditCard && !pps.date && (pps.blocksLength === 0 && !pps.prefix)) {
            return;
        }
`
It is possible to somehow set initial value for this kind of input?
Thanks a lot for any kind of help

**Comment by nosir** [comment]
Question, you are not passing any options into cleave.js, so it doesn't need to apply any format for that input? Then why not using native input field?

**Comment by Tommy10802** [comment]
Yep you are right this is a solution i am allready thinking about. I just ask you if there is no way to use cleave as ordinary input, it means less conditions for me in my code.

**Comment by nosir** [comment]
Okay, I've added the init value and init callback in that case
Released. Thanks.
https://github.com/nosir/cleave.js/releases/tag/v0.9.2

**Comment by Tommy10802** [comment]
Hello i have another problem when no options are supplied. If you initialize CleaveInput without any options you cannot type "space" char into string
