### ISSUE TITLE
Destroy function removeEventListener looks wrong

### ISSUE THREAD

**Issue by bruce-one** [nosir/cleave.js#21]
To my eye, it looks like the `removeEventListener`s in `destroy` are incorrect. [Here.](https://github.com/nosir/cleave.js/blob/f3056d86a374203082f5be7e8af1551b0c72c6e2/dist/cleave.js#L241)

(AFAIU):

The result of `owner.onChange.bind(owner)` is a new function, hence the removal is trying to remove a "different" function to the one that's attached, and hence not removing anything. Instead the result of the `bind` could be stored as a variable so that the exact save function is passed to `removeEventListener`, and hence is removed correctly.

To try and demonstrate:

```
Object.keys(getEventListeners(document.body)).length
> 0
func1 = () => console.log('a')
> () => console.log('a')
document.body.addEventListener('click', func1.bind(document))
> undefined
Object.keys(getEventListeners(document.body)).length
> 1
document.body.removeEventListener('click', func1.bind(document))
> undefined
Object.keys(getEventListeners(document.body)).length
> 1
```

vs

```
Object.keys(getEventListeners(document.body)).length
> 0
func1 = () => console.log('a')
> () => console.log('a')
bound = func1.bind(document)
> () => console.log('a')
document.body.addEventListener('click', bound)
> undefined
Object.keys(getEventListeners(document.body)).length
> 1
document.body.removeEventListener('click', bound)
> undefined
Object.keys(getEventListeners(document.body)).length
> 0
```

(Apologies if I'm being silly :-) (I haven't actually tried the library, I just noticed it... It looks neat though, awesome work, and I love the idea :-) ))

**Comment by nosir** [comment]
Oh, hmm, thanks for the PR, will test it a bit and merge.
