### ISSUE TITLE
Blocks options can't change with react

### ISSUE THREAD

**Issue by Lightclawjl** [nosir/cleave.js#210]
Hi, I'm trying to make an field for inputting a percentage value. using these options:
`{ delimiters: ['.'], blocks: [2, 2], numericOnly: true }`
Using it works just fine, until someone try to input 100% in it...
by typing 100, cleave shows 10.0, so i made a code in wich:  
If the input is 10.0, the user is probably trying to input 100, calling a function by onChange and then setting a new state.
Then my options looked like this:
`{ delimiters: ['.'], blocks: [this.state.fullSplitOpt, 2], numericOnly: true }`

I tried almost everything, but the input text won't change, it remains 10.0 or 10.00, i checked if my state was changing and it does, also not using a state and using a global variable instead didn't do the trick.
So, I'm looking for a way to change my options on the fly, can anyone help me?

*Sorry for bad english...

**Comment by nosir** [comment]
Unfortunately, cleave doesn't support changing options on the fly.
Also how would you know if the use is trying to enter 10.05 or 100?
