### ISSUE TITLE
getRawValue is returning one extra character

### ISSUE THREAD

**Issue by Mouvedia** [nosir/cleave.js#212]
config:
```
          phone: true,
          phoneRegionCode: 'FR'
```

My input shows 07 87 87 98 55 and getRawValue is returning 07878798555 because it stores the last number you add after the limit. If I type 6 in the input whilst it has reached its limit the raw value will be 07878798556.

I cannot use this library until that's fixed.

**Comment by nosir** [comment]
Can't reproduce here: https://jsfiddle.net/5opsveaq/2/
