### ISSUE TITLE
Option `numericOnly` doesn't work on it's own 

### ISSUE THREAD

**Issue by matbrady** [nosir/cleave.js#213]
Is it intended that `numericOnly` doesn't work when it's the only option supplied? I would expect that any non number keypress would still be suppressed regardless of other options. ex:
```js
var cleaveNumeral = new Cleave('.input-numeral', {
    numericOnly: true
});
```
**Here's a fiddle displaying the experience:**
https://jsfiddle.net/br8dy/pcttaqeb/2/

**Possible solutions:**
a. suppliying a `true` value to `numericOnly` would suppress non number keypresses even when it's the only option supplied. 
b. update documentation to explain which options will respect the `numericOnly` value

Thanks for the clarification

**Comment by nosir** [comment]
Thanks @matbrady I went with the option b.
https://github.com/nosir/cleave.js/blob/master/doc/options.md#numericonly
Just saying, if numericOnly is the only option in the user case, it doesn't cleave anything :)

**Comment by matbrady** [comment]
@nosir thanks for the clarification and update!
