### ISSUE TITLE
Is it compatible with ReactNative?

### ISSUE THREAD

**Issue by prscX** [nosir/cleave.js#214]
As per my understanding Cleave is compatible with ReactJS, I have not tried it with ReactNative, is Cleave ReactJS build compatible with ReactNative too?

**Comment by nosir** [comment]
Haven't got chance to check ReactNative either, I think we got an issue popped up before:
https://github.com/nosir/cleave.js/issues/214
So probably the answer is no :(
Please follow that one if you interested.

**Comment by vicentedealencar** [comment]
This is #214, what's the other issue?

**Comment by nosir** [comment]
Oh Sorry, should be here: https://github.com/nosir/cleave.js/issues/141
