### ISSUE TITLE
Date delete error

### ISSUE THREAD

**Issue by boxman0617** [nosir/cleave.js#218]
When using `Cleave` react like so:

```javascript
<Cleave
    name="date"
    placeholder="MM/DD/YYYY"
    options={{ date: true, datePattern: ['m', 'd', 'Y'] }}
    onChange={this.onChange}
/>
```

and I get the following when attempting to delete a number that is not at the end of the string:

![cleave-js-error](https://user-images.githubusercontent.com/1375632/29683918-f279806e-88c4-11e7-94f0-5058cec7d99a.gif)

Thank you for this lib btw!

**Comment by nosir** [comment]
Yea, delete/edit a number could be very tricky in the date input.
I will try to solve in this thread, you can follow this if interested: https://github.com/nosir/cleave.js/issues/219 
Thanks for the demo and love.
