### ISSUE TITLE
Make leading zeros optional

### ISSUE THREAD

**Issue by qbolec** [nosir/cleave.js#220]
In Finland the dates are written as "1.2.2017".

> Since it's an input field, leading 0 before date and month is required

https://en.wikipedia.org/wiki/Date_format_by_country

How to work around that?

**Comment by nosir** [comment]
It's hard for the lib to achieve this, the point is not to let user type delimiter, then like if someone typed in `12`, how does it know if it's `12nd` or `1st Feb`.
I think at least this is not in the plan.
Cheers.
