### ISSUE TITLE
Change mask pattern on the fly

### ISSUE THREAD

**Issue by klaygomes** [nosir/cleave.js#221]
Is it possible to change mask pattern on the fly? I would like something [like that ](http://jsfiddle.net/igorescobar/ebf0ovmj/). If you start with `04` it changes it mask pattern.

**Comment by uebbi** [comment]
I ended using:

```
$('.cpfj').on('keyup', function() {
  if ($(this).val().length <= 14) {
    new Cleave('.cpfj', {
      numericOnly: true,
      blocks: [3, 3, 3, 3],
      delimiters : ['.', '.', '-']			
    });
  }
  else {
    new Cleave('.cpfj', {
      numericOnly: true,
      blocks: [2, 3, 3, 4, 2],
      delimiters : ['.', '.', '/', '-']
    });			
  }
});
```

**Comment by uebbi** [comment]
Ops! With the solution above we've a new problem: backspace can't erase input delimiter on mobile devices :(

**Comment by nosir** [comment]
Unfortunately, changing options on the fly is not supported by the lib.
You probably need to create new instance and tweak the input values like @uebbi did.

**Comment by RicardoZambon** [comment]
Sorry update this closed topic, but adding more information in case anybody need this in the future, I was in need of a custom format accordingly to the field length.

The @uebbi  example helped, but wasn't complete, before setting the `new Cleave()` was needed destroy the previous instance.

Here is the complete code:

```javascript
var activeFormat;

$('.cpfj').on('keyup', function() {
    if (activeFormat != null) {
        activeFormat.destroy();
        activeFormat = null;
    }
    
    if ($(this).val().length <= 14) {
        activeFormat = new Cleave('.cpfj', {
            numericOnly: true,
            blocks: [3, 3, 3, 3],
            delimiters : ['.', '.', '-']			
        });
    }
    else {
        activeFormat = new Cleave('.cpfj', {
            numericOnly: true,
            blocks: [2, 3, 3, 4, 2],
            delimiters : ['.', '.', '/', '-']
        });			
    }
});
```

And here is the Fiddle example, hope this helps.

https://jsfiddle.net/Ricardozambon/kyx4c96n/

**Comment by RicardoZambon** [comment]
To fix the issue with the backspace, you must not reapply the mask format when the previous field length is equal to the current length.

I've update the fiddle with this fix.

```javascript
var oldValue = '';
if ($(this).data('old_val') != undefined) { oldValue = $(this).data('old_val'); }

var currentValue = this.value;
if (activeFormat != null) { currentValue = activeFormat.getRawValue(); }

if (oldValue.length != currentValue.length) {
    if (activeFormat != null) {
        $(this).data('old_val', activeFormat);
        ...
    }
    ...
}
```
