### ISSUE TITLE
error in snapshot tests

### ISSUE THREAD

**Issue by phillyqueso** [nosir/cleave.js#223]
I just installed 1.0.1, excited for the fixes. But now my tests fail... Looks like `owner.element` is undefined in that call stack. I checked out a local copy, added an early return check in `Cleave.react.js` line #355 `if (!owner.element) return;`, and that fixes it for me.

<img width="768" alt="screen shot 2017-08-30 at 5 02 42 pm" src="https://user-images.githubusercontent.com/516705/29897556-055fe402-8da7-11e7-9555-9b2a6306ab51.png">

--cheers! Let me know if you'd like PR

**Comment by nosir** [comment]
Hi @phillyqueso, PR welcomed.
Thanks

**Comment by nosir** [comment]
Released in https://github.com/nosir/cleave.js/releases/tag/v1.0.10

**Comment by leerob** [comment]
If no options are supplied (in React), I'm hitting the same issue. Once I add in options, the Snapshots are generated.
