### ISSUE TITLE
Missing decimal delimiter

### ISSUE THREAD

**Issue by MarkBroGT86** [nosir/cleave.js#224]
Hey Guys :)
i´m trying to format some currency input boxes.

My Goal would be:
1.250.500,86 (so with decimal)

When i´m typing i get:
125.050.086

My code:
var cleave = new Cleave('input.valueInput', {
    numericOnly: true,
    numeral: true,
    numeralDecimalMark: ',',
    delimiter: '.',
    numeralDecimalScale: 2
 });

I hope i´m not just too stupid. 

Thank you!

**Comment by nosir** [comment]
Question, how do you usually enter `1.250.500,86`?
Do you type in `.86` or `,86` on keyboard?

**Comment by nosir** [comment]
Hmm, it's been a while, closing this.
So how it works, `numeralDecimalMark` is the actual decimal mark showing in the number.
Say in some countries, decimal mark is `,`, then you will need to type `,86`

**Comment by lcvbeek** [comment]
Would like to reopen this -- in code, the decimal mark is ALWAYS a period. Commas are reserved for other syntax. So for a 'number' type with a decimal value, it should always read the period as a decimal mark... IMO typing periods or commas should always mean 'decimal' if the formatter automatically corrects the resulting number.

**Comment by nicknick-io** [comment]
> Would like to reopen this -- in code, the decimal mark is ALWAYS a period. Commas are reserved for other syntax. So for a 'number' type with a decimal value, it should always read the period as a decimal mark... IMO typing periods or commas should always mean 'decimal' if the formatter automatically corrects the resulting number.

In Denmark we do it differently.
What you know as **10,000.00** would be **10.000,00** in my case. And then we would convert it back into **10000.00** when we save it.
