### ISSUE TITLE
[Bug] setRawValue for date input not working correctly in React

### ISSUE THREAD

**Issue by Liooo** [nosir/cleave.js#226]
Calling setRawValue when the input value is like "YYYY/M" or "YYY" make it weird as below. (Assuming these are the cases that the input value is 1 character away from where the delimiter is inserted.)
Here's [JSFiddle](https://jsfiddle.net/wqm8pm6c/9/).

![cleave](https://user-images.githubusercontent.com/1630378/30313315-d663f43c-97d7-11e7-83ef-56d12607b2fe.gif)

**Comment by nosir** [comment]
Merged fix, thanks.
