### ISSUE TITLE
'engines' in package.json prevents installation with yarn 1.X

### ISSUE THREAD

**Issue by ryami333** [nosir/cleave.js#228]
Trying to install this package with the recently release Yarn 1.X, the following error is encountered:
```
error web-app@0.1.0: The engine "yarn" is incompatible with this module. Expected version "^0.27.5".
error Found incompatible module
```

AFAIK, this is a mis-appropriation of the 'engines' property, and I think you ought to remove it.

**Comment by crazyyi** [comment]
Similar issue found here:

```
error pre-release@0.0.1: The engine "yarn" is incompatible with this module. Expected version "^0.27.5".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
Don't have a clue what this means.

**Comment by ryami333** [comment]
Was nonsense sorry, will close.

**Comment by crazyyi** [comment]
@ryami333 what do you mean was nonsense? How did you fix this?

**Comment by ryami333** [comment]
It wasn't broken, I was just being an idiot. I was trying to install the package while my yarn version mis-matched my own `package.json`'s engine value. Classic PEBKAC issue.
