### ISSUE TITLE
Credit Card Prefix Issue

### ISSUE THREAD

**Issue by WeeHong** [nosir/cleave.js#233]
I found there is a credit card prefix issue when you type in 1111111111111111.

It does not mask it into 1111 1111 1111 1111

Also, whenever there is a number starting with 1 after 4 digits. It got the issue to mask.

Please refer to the image below.

![image](https://user-images.githubusercontent.com/6753022/30700950-a80ff4d2-9f1b-11e7-9194-20a3756066a2.png)
![image](https://user-images.githubusercontent.com/6753022/30700976-bd2a6ee2-9f1b-11e7-9d49-11959ae18034.png)

**Comment by GregoireHebert** [comment]
Hi @WeeHong 

Everything seems correct to me.
The UATP credit card number format is 15 digits starting by a 1.
And according to the IIN Ranges & Spacing Patterns, it's 3 blocks of 4, 5 and 6 digits.

If you are looking for a card not handled, feel free to do a PR :)
I had to do it myself today .

**Comment by nosir** [comment]
Just as @GregoireHebert said, it has to be an exact credit number.
