### ISSUE TITLE
Backspacing removes 2 characters 

### ISSUE THREAD

**Issue by ratneshraval** [nosir/cleave.js#234]
Example cursor position: (342) 232-|
Press backspace: 
Expected result:  (342) 23|
Actual result:  (342) 2|

 options={{
            delimiters: ['(', ')', ' ', '-'],
            blocks: [0, 3, 0, 3, 4],
            numericOnly: true}}

Anyone else experiencing this?

**Comment by iamdubx** [comment]
It looks like issue with space in delimeter. I have similar issue.

**Comment by nosir** [comment]
Can't reproduce here: https://jsfiddle.net/qhLja8vu/1/

**Comment by nosir** [comment]
Will close this, seems this got fixed with some later deployment

**Comment by ratneshraval** [comment]
Agree. Was able to verify the fix with latest version. Thank you!
