### ISSUE TITLE
Problem with blocks and cursor position after select and delete

### ISSUE THREAD

**Issue by asso1985** [nosir/cleave.js#236]
First of all guys, great project here.

Just wanted to report an issue that probably you are already aware of :

This is my configuration : 

`maskOptions = {
    delimiters: [' ', ' '],
    blocks: [4, 4, 4],
    uppercase: true
  }`

And this is the Issue that you should be able to see reproduced here 

https://s.nimbus.everhelper.me/share/1140653/0gwq79uecmrkkwb1vioe

So 

- selecting with double click the center block
- backspace

first next character is written down (1 in the example) but cursor position is wrong.

Let me know if I can help

**Comment by asso1985** [comment]
This seems to happen only if delimiters are empty spaces.

**Comment by nosir** [comment]
Thanks for the demo.
There was an issue created here, please track here: https://github.com/nosir/cleave.js/issues/219
So will close this one.
Cheers

**Comment by nosir** [comment]
Fixed release: https://github.com/nosir/cleave.js/releases/tag/v1.2.0
