### ISSUE TITLE
Issue when deleting using delimeters with spaces.

### ISSUE THREAD

**Issue by iamdubx** [nosir/cleave.js#237]
Hello. If you type phone number and then try to delete it with Backspace you will have an glitch behavior. 

How it can be fixed? I can't use spaces in delimeters? 

https://jsfiddle.net/ywb0fcjq/

**Comment by nosir** [comment]
Can you please try this?
`{blocks: [3, 0, 3, 0, 3, 2, 2], delimiters: [' ', '(', ')', ' ', '-'], prefix: '+38'}`

**Comment by iamdubx** [comment]
@nosir great, thanks!
