### ISSUE TITLE
Need to double tap to delete delimiters on Android.

### ISSUE THREAD

**Issue by iamdubx** [nosir/cleave.js#239]
If I am deleting input then I need to do double tap to delete delimiter. Why is this happening and how it can be fixed?

Android 6.0.1, Chrome

**Comment by nosir** [comment]
There are some fixes only applied for Android devices, so the behaviours could be different from desktop/iOS version.
Guess as long as the main function doesn't break, it will keep like this at this moment.
Cheers.
