### ISSUE TITLE
Dayinput inconsistent? (33 turns to 31, 44 turns to 04/04)

### ISSUE THREAD

**Issue by escapedcat** [nosir/cleave.js#240]
https://jsfiddle.net/nosir/kbaxx64s/

If you input `33` in the datefield it turns to `31` not (`03/03/`).  
But if you put in `44` it turns to `04/04/`.  

Is this done on purpose? If yes what's the reason? If not, would it make sense to adjust this behaviour?

I'm not sure if I'm missing something here... thx for a reply and much bigger thanks for creating this awesome lib!

**Comment by nosir** [comment]
Hey @escapedcat 
I think it's more about how the lib handles the date check, the default pattern is day/month/year.
The moment you entered `4`, it clearly knows if must be date `04`, so it changes to `04` immediately for you, but when you entered `3` it can't decide if it's `03` or could be `30` or `31` so it has to wait until the second digital has been entered.
This two scenarios trigger the different auto fix way, and this is the reason.
I think we will keep it as it is for now.
Thanks for the love.

**Comment by escapedcat** [comment]
Sure, but why does `3x` for example `33` into `31`?  
The maximum of days per month is *31* (or maybe *32* in some edge-cases?), so every number after a `3` besides `0`, `1` (or `2`?) should lead to the next field I think.   
Just wanted to add this to make my point a bit clearer.   
  
I also totally agree that this isn't very important or a bug ;)
