### ISSUE TITLE
Caret get lost when typing in the middle of a number

### ISSUE THREAD

**Issue by alexandresebrao** [nosir/cleave.js#243]
I'm trying to implement Cleave on my project but got a problem.

When typing in the number in a position different than the end, the caret doesn't stay at the desire position, after a delimeter it's added or removed, it moves to another position.

Evidence on the image below:
![cleave](https://user-images.githubusercontent.com/8672455/31337753-18c10f9e-acd3-11e7-9a8d-a90a9222c665.gif)

PS: Great work on Cleave, it's a great library.

**Comment by timsnadden** [comment]
Please have a look at https://github.com/nosir/cleave.js/pull/262 

I believe this fixes the issue

**Comment by alexandresebrao** [comment]
I can't be sure if it will as I don't use the react one, I create my wrapper since my input has other functionalities and specifics styles then the builtin on cleave

**Comment by nosir** [comment]
This is duplicated, please track the issue here: https://github.com/nosir/cleave.js/issues/219
Will close this, and thanks for the like :) @alexandresebrao.

**Comment by nosir** [comment]
Hi guys, fixed release: https://github.com/nosir/cleave.js/releases/tag/v1.2.0
