### ISSUE TITLE
Custom date format; time support

### ISSUE THREAD

**Issue by Scit** [nosir/cleave.js#246]
1) Now Cleave provides the only delimiter for date parts: slash (/). Another symbols are not supported yet?
For example: 18-10-2017?
 
2) What about time values support?

**Comment by nosir** [comment]
1. 
```
new Cleave('.my-input', {
    date: true,
    delimiter: '-',
    datePattern: ['d', 'm', 'Y']
});
```

2. Unfortunately, time support is not in the plan.

**Comment by Scit** [comment]
@nosir thank you for answer!

**Comment by indivine** [comment]
+1 for time options. We run a major listings website which requires inputs for opening hours of businesses. Please add this

**Comment by nosir** [comment]
Time supporting released, please check: https://github.com/nosir/cleave.js/issues/73#issuecomment-405003687
