### ISSUE TITLE
Some Users Experiencing Looping issue

### ISSUE THREAD

**Issue by redluss** [nosir/cleave.js#248]
Hello-

Honestly not sure if this is coming from the library or not, but hoping you might have some ideas. I have some reports - likely from folks on older browsers - who are tabbing between number fields with thousands separators being applied. Somehow their browsers are getting locked in a loop where the cursor jumps from one field to the next and eventually it locks up and crashes the browser (appears to in most cases based on reports). It's happening to maybe 1 out of 30 users on the system. Any ideas what might be going on?

Thanks.

**Comment by eugene1g** [comment]
If you have onBlur events, or re-render the parent component housing all your input fields, it might be related to https://github.com/nosir/cleave.js/issues/225#issuecomment-338484595 In some browsers (e.g. Safari and IE 11) Cleave will force the browser to send focus/cursor into the input field every time the component is rendered.

**Comment by redluss** [comment]
I have finally been able to replicate the issue - would appreciate any thoughts.
I have a form with several fields all with the same selector - .currencyformat
When a user tabs from the first field to the second WITHOUT inserting a value in the first field, it locks in a loop, jumping from the first field to the second and back again. This only appears to happen in IE.

Here is the Cleave script I'm using...
`
$(document).ready(function() {
	$('.currencyformat').on('input', function(event) {
		var target = event.target;

	 new Cleave(target, {
			numeral: true,
			numeralThousandsGroupStyle: 'thousand'
			});

	}); //end currency
}); //end document ready function Cleave`

Any idea why this might be happening? I've played with several methods for stopping it, but can't seem to make them work.

**Comment by nosir** [comment]
In your case target should be a unique DOM element. If you want to apply Cleave for multiple elements, you need to give different css selectors and apply to each of them.
Have you tried this?

**Comment by brandonros** [comment]
I also experience this, but in Angular.

**Comment by redluss** [comment]
So I've found a fix - whether or not this is what's causing it - but what I found was that in Internet Explorer, the issue occurs as a part of onInput. If I change it to onKeyup, it performs without issue. Hopefully this will help others solve the issue in the future.

Worth mentioning, I found an article somewhere that someone else wrote that indicated the onInput issue is quasi-known for IE.
