### ISSUE TITLE
React.js on mobile devices after first entry error

### ISSUE THREAD

**Issue by smanunta** [nosir/cleave.js#250]
on mobile devices tested on Android and Iphone. When entering a number the keyboard goes back to letters when further numbers need to be entered. 

I tested this on your fiddle as well and the issue is persistent.
 https://jsfiddle.net/nosir/gLLsrxxf/ 

Is there a fix for this

**Comment by nosir** [comment]
iOS and Android env please?
Tested on iPhone6 iOS 10, 11, can't reproduce

**Comment by nosir** [comment]
Hmm, it's been a while, also still can't reproduce.
Must be fixed during a past release, closing this.
