### ISSUE TITLE
redux-form failing after setRawValue

### ISSUE THREAD

**Issue by ah-adarlow** [nosir/cleave.js#251]
I have a Cleave React component inside a redux-form form. It works great until I call `setRawValue`. Then the input goes blank. The use case is a date input with a shortcut that fills in today's date if the user presses 't'.

After some investigation, I found that the onChange "event" triggered when calling setRawValue, isn't actually an Event object of any kind, but simply an object of the shape 
`{ target: { rawValue: '10192017', value: '10-19-2017' }`
redux-form recognizes that it isn't an event object and therefore sets the entire "event" object as the value of the field, instead of just the value. When it tries to set that object as the value prop in the Cleave component, it obviously fails.

One possible solution would be to call `dispatchEvent` on the input to trigger a real event. This seems the most elegant solution in some ways, but violates the contract that DOM `input` events are only triggered by user actions. Does anyone know a better way to trigger an event in React?

An alternative workaround would be to fool redux-form by adding `stopPropagation` and `preventDefault` properties to the "event" object. See https://github.com/erikras/redux-form/blob/82259fbac0a53b583c2b52738522fedbd35f8c40/src/events/isEvent.js
This is less than ideal because it relies on implementation details that might change.

I'm happy to implement any agreed-upon solution.

**Comment by nosir** [comment]
Hey @ah-adarlow Sorry for a bit delay.
I would suggest we go for the second solution you proposed, me the same, as you said, not a big fan of interfering too much native DOM events here.
Surely PR welcomed.

**Comment by nosir** [comment]
Thanks @ah-adarlow
