### ISSUE TITLE
Only show delimiter if enough characters

### ISSUE THREAD

**Issue by richthedev** [nosir/cleave.js#261]
Hi, thanks for the awesome lib!

Is there any way to only show a delimiter when there are more characters than a block can hold ? For example, I built a custom phone format like so:
`{ blocks: [3, 3, 4, 3], delimiters: ["-", "-", "x"], numericOnly: true } `

I would like the field to display `555-123-4567` when no extension is present and `555-123-4567x999` when a user enters an extension number.

**Comment by nosir** [comment]
@richthedev Thanks for the like.
I'm adding the feature, will deploy by the weekend.

**Comment by nosir** [comment]
https://github.com/nosir/cleave.js/blob/master/doc/options.md#delimiterlazyshow
Released in https://github.com/nosir/cleave.js/releases/tag/v1.1.0
Closing this, let me know if there is any problem.
Cheers

**Comment by richthedev** [comment]
Sorry, should have read the documentation more thoroughly.

**Comment by nosir** [comment]
@richthedev Na, wasn't your miss.
I just added it during the weekend. This is new feature. :)
