### ISSUE TITLE
stripLeadingZeroes issue with numeral input

### ISSUE THREAD

**Issue by danplaseg** [nosir/cleave.js#263]
stripLeadingZeroes property for the numeral input is not working in cleave.min.js.

I have took a peek to the two versions of the file, and it's present on the constructor for the unminified version, but it's not in the minified one.
As expected, in the minified version this option does nothing and the numbers starting with zeroes are being stripped anyways.

**Comment by nosir** [comment]
Can't reproduce here: https://jsfiddle.net/uwz5mdws/3/ which is linking to `cleave.min.js`
Set `stripLeadingZeroes` to false preserve the leading zeros.
