### ISSUE TITLE
Prefix contains number

### ISSUE THREAD

**Issue by medinsky** [nosir/cleave.js#266]
With chars it work good. 
But when I want to set prefix '21' for example

`new Cleave('.postcode', {
        numeral: true,
        prefix: '21',
        delimiter: '',
        numeralPositiveOnly: true
    });`

it dublicates 21 before each number entered in the field
211212213214215

**Comment by nosir** [comment]
I think you shouldn't use `numeral` type, since it's postcode not a real numeral number.
I don't know how's your postcode format but you can try this:
`{prefix: '21', delimiter: '', numericOnly: true}`
