### ISSUE TITLE
Build customized country group

### ISSUE THREAD

**Issue by perrosen** [nosir/cleave.js#267]
Hi,

Thanks for the awesome library! Was looking at implementing the phone number formatting and wanted to limit what countries was included in my bundle since I don't need them all. 

Following the link below though you seem to be lacking documentation for this. 

https://github.com/nosir/libphonenumber-country-metadata#build-phone-type-formatterjs-for-cleavejs

Will be adding more and more countries in the future so would need to do this every now and then and if it can be explained here I would be more than happy to create a PR for updated documentation :)

**Comment by nosir** [comment]
Hi @perrosen
Seems I didn't add that feature before :p 
It's updated now, and the doc is updated with a demo: 
https://github.com/nosir/cleave.js/blob/master/doc/phone-lib-addon.md#customize-building

**Comment by nosir** [comment]
Closing this, feel free to open if you have any problem in generating.
