### ISSUE TITLE
Phone number formatting breaks when selecting some regions.

### ISSUE THREAD

**Issue by JacquesMarais** [nosir/cleave.js#27]
There are some regions that breaks the phone number formatting when a plus sign isn't added before. To see this, go to the second demo at [http://nosir.github.io/cleave.js/](http://nosir.github.io/cleave.js/) and select one of the last regions, like ZW or ZA.

**Comment by trjiang** [comment]
Hi, @JacquesMarais can you please provide the number you entered?

**Comment by JacquesMarais** [comment]
@trjiang Well any number really.

It breaks because the length isn't limited to 10 characters and the number isn't given spaces inside, for example, enter `483938827248829`.

**Comment by trjiang** [comment]
Without country code +xxx, you will need to add leading 0, which can't be omitted. So it should be 048393........

https://en.wikipedia.org/wiki/Telephone_numbers_in_South_Africa

Also, you can also test it in google libphonenumber test page:
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

I will close the issue.

**Comment by JacquesMarais** [comment]
This still happens when adding a zero though: `08888888888877888`

**Comment by trjiang** [comment]
I put your number here: https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
And tried both `ZW` and `ZA` none of them seems to be a valid number.

**Comment by JacquesMarais** [comment]
Oh I see now, so it validates the numbers by country. Thanks!
