### ISSUE TITLE
uncontrolled input (ref) doesn't work with cleave in react

### ISSUE THREAD

**Issue by malmeb** [nosir/cleave.js#270]
I have a cleave input that I need to use as an uncontrolled input because I need to re-focus the input several times depending on user actions (ie the autofocus attribute will not work for me)

If you try to focus the cleave input, or wants to read the input value and doing that from ANOTHER event than the onChange on the cleave input (for example from a button click event) it will not work.

Example with working regular input and not working cleave input: 
https://jsfiddle.net/rwqz84do/1/

**Comment by nosir** [comment]
Hey @malmeb thanks for providing a jsfiddle url 👍 
Please check this: https://github.com/nosir/cleave.js/blob/master/doc/reactjs-component-usage.md#how-to-get-ref-of-the-input-field

**Comment by malmeb** [comment]
Thank you @nosir, I apologize I didn't saw that in the documentation! Great lib!

**Comment by nosir** [comment]
That's cool and thanks for the like
