### ISSUE TITLE
What is data-cleave-ignore?

### ISSUE THREAD

**Issue by morrisallison** [nosir/cleave.js#274]
The react component sets an attribute named `data-cleave-ignore`. The attribute doesn't seem to be used by anything, and clutters up the DOM.

![image](https://user-images.githubusercontent.com/3189455/32965597-d6a337b8-cb8b-11e7-922b-a114a4ea10e7.png)

**Comment by nosir** [comment]
Something set to bypass eslint... 
Fix released in v1.0.7
