### ISSUE TITLE
No option for adding trailing zeroes with numeralDecimalScale?

### ISSUE THREAD

**Issue by rseyferth** [nosir/cleave.js#275]
Great plugin! But I have some inputs that are used for entering currency values and I would like the numbers to be always formatted with 2 decimals (e.g. € 15,50). 

So, in this example (https://jsfiddle.net/h7d9gn03/) I would like the input to show 12.50 instead of 12.5. There is no option for that, is there? Any plans to add this feature?

**Comment by nosir** [comment]
Looks like a good option to have, it's ongoing.

**Comment by nosir** [comment]
Sorry, I think this was up in a previous release 😃, but you will need to pass a string as raw value, in your case `'12.50'`:
https://jsfiddle.net/sxeubwq1/

**Comment by nosir** [comment]
Close this, let me know if you still have problem.

**Comment by Shurasik** [comment]
Hi,
Same issue for me, I didn't understand how to fix this.

Desired behavior: the user types in 1234 -- as soon as "1" is keyed in ".00" is appended, as soon as "4" is typed in the comma is appended (the comma works well), end result is 1,234.00.

I don't know if the user experience will be good with the above behavior so maybe a better version would be that once they tab away from the input field (i.e., onblur() is called) either .00 is appended if the input is an integer, or "0" is appended if the input has a tenth part and not a hundredth part (e.g., 12.5)
Please let me know if cleave can achieve something like what I described above, I need this in real time or onblur. It sounded like the proposed solution mentioned above was static and didn't apply to my case.

I will probably write my own extension to conditionally add the .00 or 0 onblur(), just wanted to see if there was a built in option for this, I didn't see it in the documentation.

Thank you!
Sasha

**Comment by nosir** [comment]
@Shurasik Unfortunately, no built-in option is like that, the lib only handles the formatting.
Cheers.
