### ISSUE TITLE
Android: Problems with number delete

### ISSUE THREAD

**Issue by lovelyun** [nosir/cleave.js#279]
problem: Can not delete when there is a space
system: android 4.4.4
UA: Mozilla/5.0(Linux;Android 4.4.4;m1 Build/KTU84P)AppleWebkit/537.36(KHTML,like Gecko)Version/4.0 Chrome/33.0.0.0 Mobile Safari
example: input formated like this,"111 222 333",now delete,when it comes to"111 222 ",it cann't delete anymore.the space always there.

**Comment by lovelyun** [comment]
I can upload a video for details if you need

**Comment by nosir** [comment]
Hey @lovelyun there was a few releases might cover the fix, would you mind test it again and let me know. Thanks
