### ISSUE TITLE
Last letter of prefix gets pushed out when typing into the prefix itself

### ISSUE THREAD

**Issue by toastyghost** [nosir/cleave.js#28]
Go to the demo site, scroll down to the "prefix" demo.
Click anywhere inside the word "prefix" in the textbox.
Start typing. Note that even though Cleave correctly removes the letters you typed into the prefix, it keeps the 'X' that got pushed out past the dash.

**Comment by nosir** [comment]
Released in v0.6.12
Cheers @cht8687
