### ISSUE TITLE
Prefix - Odd data entry behavior

### ISSUE THREAD

**Issue by dballardgh** [nosir/cleave.js#281]
This can be seen on the demo page http://nosir.github.io/cleave.js/. For the "prefix" example:

Click on the input box to the right of "PREFIX-". Enter some characters. Use backspace to delete those characters.
-- Works as expected. Additional backspace does not affect "PREFIX-".

Click on the input box to the left of "PREFIX-". Cursor locates to the left of "P".
-- Is this intended? Shouldn't cursor be located to right of "PREFIX-"?

Enter characters 1234.
-- Value shown in input box is "PREFIX-4321". 

Click backspace once:
-- Value shown is "PREFIX-I21"

Click backspace again:
-- Value shown is "PREFIX-F1"

Click backspace fourth time:
-- Value shown is "PREFIX-R"

**Comment by nosir** [comment]
It's hard to check and control cursor location when user clicking in between `prefix`.
But as you said, I think at least we should apply a fix to locate the cursor to right of "PREFIX-", when the field obtains the focus.
Will add soon.

**Comment by nosir** [comment]
Released: https://github.com/nosir/cleave.js/releases/tag/v1.1.4
