### ISSUE TITLE
Releases page is stuck at version 1.0.2

### ISSUE THREAD

**Issue by bridgeport** [nosir/cleave.js#282]
Thanks for this great script. FYI, your releases page ( https://github.com/nosir/cleave.js/releases ) is stuck at version 1.0.2, even though CDNJS and NPM is bumped to the latest version (v1.0.9).

Also, do you happen to have the release notes between v1.0.2 and the current version? Thanks.

**Comment by nosir** [comment]
Hey @bridgeport Thanks.
Check it out here: https://github.com/nosir/cleave.js/releases/tag/v1.0.9
I agree this needs to be updated when bumping version in the future :p

**Comment by nosir** [comment]
Closing this, let me know if there is any further questions.
