### ISSUE TITLE
"required" cleave fields have a red border/box-shadow in Firefox on initialization

### ISSUE THREAD

**Issue by bridgeport** [nosir/cleave.js#283]
On page load, any input that has cleave.js applied to it will have a red `:invalid` border (actually box-shadow) in Firefox. I tested in Firefox v57 using cleave.js v1.0.9.

BTW, this is happening in Firefox Mobile (on Android) too.

You can reproduce it in Firefox by:

1. visiting the basic demo: https://jsfiddle.net/nosir/kbaxx64s/
2. Add a "required" attribute to the fields.
3. Rerun the page

I assume cleave.js is somehow modifying/touching the fields that in some way triggers Firefox to immediately mark the fields as valid.

The browser's internal CSS style is applied using `:-moz-ui-invalid`:

https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-ui-invalid
https://stackoverflow.com/questions/6915200/what-css-is-used-by-browsers-for-styling-invalid-input-type-emails

Thanks.

**Comment by nosir** [comment]
Good report.
Released in https://github.com/nosir/cleave.js/releases/tag/v1.0.10
Cheers
