### ISSUE TITLE
Angular module doesn't work with AMD

### ISSUE THREAD

**Issue by patstuart** [nosir/cleave.js#284]
If AMD is defined in the browser, the compiled code attaches Cleave to define, not to the window:

    //...
    else if(typeof define === 'function' && define.amd)
        define([], factory);
    //...
    else
        root["Cleave"] = factory();

But the Angular plugin incorrectly assumes it is attached to the window in all cases.

    $scope.instance = new window.Cleave($element[0], $scope.cleave());

This causes a TypeError.

    angular.js:14700 TypeError: window.Cleave is not a constructor
        at Object.pre (cleave-angular.js:1138)
        at angular.js:1385

Fix: The plugin should not assume that Cleave is attached to the window. Instead, it should use the same path as `webpackUniversalModuleDefinition` uses.

**Comment by nosir** [comment]
Fix released in https://github.com/nosir/cleave.js/releases/tag/v1.2.1
Demo: https://github.com/nosir/angular-requirejs-seed (check out master, `yarn` and `bower install`), `app/index.html`
