### ISSUE TITLE
Can this be used as a string formatter?

### ISSUE THREAD

**Issue by hristod** [nosir/cleave.js#289]
I'd like to use this formatter together with redux-form. For this case, I'd need to use it without attaching to a real <input> field, is this possible? To make it more clear: I need to use this module with string input and string output, without attaching it to a <input>. Thanks in advance!

**Comment by nosir** [comment]
Hey @hristod 
The lib doesn't provide standalone string formatter itself.
If you are only seeking to use it with redux-form, would any of the solutions fit your needs here?

https://github.com/nosir/cleave.js/issues/159#issuecomment-313679815
https://github.com/nosir/cleave.js/issues/159#issuecomment-326487309

**Comment by nosir** [comment]
Will Close this, let me know if you still have any problem in integrating this with redux-form.
