### ISSUE TITLE
Value should also be updated in componentWillReceiveProps [cleave.react]

### ISSUE THREAD

**Issue by alterx** [nosir/cleave.js#29]
As you can see [here](https://facebook.github.io/react/docs/component-specs.html#getinitialstate), the getInitialState function is only called once so, if the `value` prop changes after the component is initialized this wont be reflected in the cleave react component value. This happens, for example, when sending initalValues inside a redux-form component and effectively prevents the cleave react component to be initialized with the adequate initial value.

**Comment by nosir** [comment]
I guess the main problem is the `value` change in react component can't be taken by cleave.js, saw your PR, will test it a bit and merge, cheers.

**Comment by alterx** [comment]
Yeah, sometimes, the `value` is updated after the cleave component is initialized and, in this specific case, it wont pick the correct `value`. Awesome!

**Comment by jlubeck** [comment]
Hey @alterx, do you mind sharing how you implemented Cleave with react-redux?
Thanks!

**Comment by alterx** [comment]
@jlubeck, sadly it was for an internal project so I can't show you the code right now. 
I remember we just had a couple of custom components wrapping Cleave (such as` CreditCardInput`) that allowed us to quickly use them without having to configure the cleave opts multiple times.

The problem that we had was that the initial value was being sent after the component was initialized so cleave wasn't picking it up. But this was fixed with the PR. The fact that we're using redux or not shouldn't affect how this works.

Do you mind sharing what's the issue you're facing?
