### ISSUE TITLE
Masking/Hiding Value

### ISSUE THREAD

**Issue by jonnycraze** [nosir/cleave.js#290]
Hopefully a simple question here:

Does Cleave have the ability to mask a value in an input after it has been typed, similar to a password input type.

so for example if someone typed in a credit card number it would be masked like:
####-####-####-1234

Thanks very much

**Comment by eugenefilimonov** [comment]
trying to figure this as well

**Comment by nosir** [comment]
Hmm, unfortunately this is not supported by the lib :)
Thanks for the like tho, closing this.

**Comment by abhinukala** [comment]
@nosir Will there be any support for this feature?

**Comment by nosir** [comment]
@abhinukala sorry, this is not in the plan.

**Comment by karlkras** [comment]
@nosir so before I go and fork this repo to add the password masking I'm curious why Cleave doesn't support this? It would seem to be a relatively straightforward process especially given what Cleave does. Have an optional param the user sends in for 'pw' with, e.g., the replacement character, and do the substitution on key entry.

**Comment by srakl** [comment]
trying to figure this out as well

**Comment by msahores** [comment]
Hi, any news on this request @karlkras ? Did you manage to get a solution? Thanks!
