### ISSUE TITLE
Angular module doesn't update on cut event

### ISSUE THREAD

**Issue by patstuart** [nosir/cleave.js#291]
The Angular module doesn't update on cut event. This is unique to the cut event; the issue doesn't replicate with drop, paste, keyup, etc.

To reproduce the error: 

- Go to https://jsfiddle.net/nosir/q58sh22t/. 
- Type something into the credit card field. 
- Cut the value (using Ctrl-X or the mouse).

Expected behavior: The model is updated with the value in the textbox.
Actual behavior: The model is not updated.

**Comment by nosir** [comment]
@cht8687 Any idea of this? I'm pretty junior in Angular :p
I have a quick solution for this: attach `ng-cut` to the input field and manually set the model value within that, and it works. Well if it's acceptable.

**Comment by cht8687** [comment]
@nosir  Perhaps need add [ngCut](https://docs.angularjs.org/api/ng/directive/ngCut) event support.

**Comment by nosir** [comment]
Hey guys, so there was an update to add an option to thoroughly support event listening:
https://github.com/nosir/cleave.js/blob/master/doc/options.md#onvaluechanged
So in your angular app: https://github.com/nosir/cleave.js/blob/master/doc/angularjs-directive-usage.md#how-to-get-formatted-value

More discussion here: https://github.com/nosir/cleave.js/pull/306
Released in v1.3.2
