### ISSUE TITLE
19-digits Credit Cards

### ISSUE THREAD

**Issue by sebastianMoser** [nosir/cleave.js#294]
Please see this article eg: https://www.adagetechnologies.com/19-digit-credit-cards-prepare-commerce-site/

Credit cards now can have up to 19 digits (not only visa).

**Comment by zetoke** [comment]
@sebastianMoser https://github.com/nosir/cleave.js/blob/master/doc/options.md#creditcardstrictmode
https://github.com/nosir/cleave.js/blob/master/src/shortcuts/CreditCardDetector.js#L63

**Comment by sebastianMoser** [comment]
This does not affects Visa cards only:

> Visa (and a few other issuer’s) card number length possibilities will now range from 12 to 19-digits.

**Comment by nosir** [comment]
I think what @zetoke trying to say is: you can always set
```
new Cleave('.my-input', {
    creditCard: true,
    creditCardStrictMode: true
});
```
to enable 19 digits formatting, and this option is not only limited to Visa

**Comment by nosir** [comment]
Released: https://github.com/nosir/cleave.js/releases/tag/v1.1.5
https://github.com/nosir/cleave.js/blob/master/doc/options.md#creditcardstrictmode
