### ISSUE TITLE
Custom numeralDecimalMark don't work.

### ISSUE THREAD

**Issue by cy6eria** [nosir/cleave.js#297]
In case, when cleave is a controlled input and a user inputs some value with custom numeralDecimalMark (e.g. comma) this symbol just ignors.

Example: https://jsfiddle.net/gLLsrxxf/343/

**Comment by nosir** [comment]
Internally, cleave is a controlled input, it maintains the React input `value` by itself, so externally, it's not necessary to set `value` attribute to the component anymore.

And you are supposed to get data and send to backend from the `state` you defined.

https://jsfiddle.net/ct8et6da/

Closing this, please let me know if you need further help.

**Comment by cy6eria** [comment]
Sounds like I can't change Cleave's value on the go.  And, for me, It's not cool. I can describe some cases when it could be useful, e.g. 'User inputs the amount in dollars, changes a currency in a dropdown, my script recalculates the amount in a new currency and replaces the amount'. Does it make sense?

**Comment by nosir** [comment]
That makes sense, is this something you are looking to solve?
https://github.com/nosir/cleave.js/blob/master/doc/reactjs-component-usage.md#how-to-update-raw-value

**Comment by cy6eria** [comment]
Oh, okay. It looks like a solution, but look at my example (https://jsfiddle.net/gLLsrxxf/483/). In the doc It was said: `there is no data binding between the value attribute`, but you can see, that not true.

**Comment by cy6eria** [comment]
I wanna say that it's okay, it's solution, but it looks more like a bug.
