### ISSUE TITLE
Number Formatting: cursor jumping

### ISSUE THREAD

**Issue by GreggOrdHume** [nosir/cleave.js#298]
**Issue**
On the cleave.js demo site at the Number Formatting section [here](http://nosir.github.io/cleave.js/) when entering the value of 1000.20 and then changing it back to 100.20 by removing the 0 before the decimal point . note how the cursor jumps over the decimal point and then overwrites them when you continue inputing digits.

**Reproduce**
```
1. Go to cleave.js demo page
2. Scroll down to Number Formatting section
3. enter in the value: 1000.20 (it will reflect as 1,000.20)
4. backspace the 0 before the .20
5. note the cursor jump to over the decimal point .
6. then typing digits overwrite the .20 decimal points
```

**Expected Result**
```
The cursor to not jump over the decimal point when removing the integer just before the decimal point.
```

**Comment by nosir** [comment]
Thanks, please follow up here, there will be a fix soon:
https://github.com/nosir/cleave.js/issues/219

**Comment by nosir** [comment]
Fixed release: https://github.com/nosir/cleave.js/releases/tag/v1.2.0
