### ISSUE TITLE
numeralDecimalMark doesn't works in Cleave React

### ISSUE THREAD

**Issue by vaibhav-systango** [nosir/cleave.js#300]
<Cleave disabled value={amount.toString()} options={{ numeral: true, numeralDecimalMark: ',', delimiter: '.' }} />
Here's the JSX component I'm using
Input: 1793.2199

Expected Output: 1.793,2199
Actual output from cleave: 17.932.199

When I remove numeralDecimalMark & set delimiter to ',' everything works fine.

Please fix numeralDecimalMark prop for Cleave React
@nosir @jasongi-at-sportsbet @reborg

**Comment by jasongi-at-sportsbet** [comment]
I don't think this is specific to Cleave React. Was this previously working? Could be related to the commits @nosir made a few weeks ago about delimiter lazy show mode. Might be worth writing some unit tests for this that fail so we can fix it.

**Comment by vaibhav-systango** [comment]
Well I just used this with React, Please update once it starts working.
Thanks

**Comment by jasongi-at-sportsbet** [comment]
I just tested this, this isn't a bug. Cleave won't convert '.' into a ',' - that isn't what it was made to do. You need to press the numeralDecimalMark key in order for it to register. If you change the delimiter to '.' then when you press '.' it's going to register as a thousands separator, not a decimal place.

**Comment by vaibhav-systango** [comment]
@jasongi-at-sportsbet ok thanks, for my use I made a regex here.
