### ISSUE TITLE
Cursor Jumping issue

### ISSUE THREAD

**Issue by shaileshrathod128** [nosir/cleave.js#301]
Hello,

I'm facing one issue with this lib, the initial value in input is **123** now if I put my cursor after **1**
and typing **987**, So the expected result should be **198,723**, but actual result is **187,923**
Please see the attached **GIF**

![cleave issue](https://user-images.githubusercontent.com/3207648/35963599-45fa32fc-0cdb-11e8-9787-3e54fae294fb.gif)

**Comment by g105b** [comment]
It's OK this issue has been closed a couple of years ago https://github.com/nosir/cleave.js/issues/25#issuecomment-256303483

**Comment by dikirill** [comment]
So, why this broken example on a demo page?
Now try to use backspace there.
Comma breaks it.

**Comment by g105b** [comment]
I was being sarcastic. Lots of people were/are complaining about this simple issue but it was deemed fixed on Oct 24, 2017.

**Comment by nosir** [comment]
So what happened:
Before https://github.com/nosir/cleave.js/issues/25, `cursor moving` didn't work at all, all cases where the user edits the contents were broken.

Thanks to @reborg and @mdziekon 's PR, they got most of the cases work but still not perfect, so I create the other issue to follow up: https://github.com/nosir/cleave.js/issues/219

This issue has never been closed and deemed fixed.

@g105b Thanks for your feedback. I apologise for the delay of the fix and somehow got you feel your comment was ignored.

I will look into those 2 PR and apply the fix based on them.

Aiming to fix this by the week.

**Comment by nosir** [comment]
Hi guys, fixed release: https://github.com/nosir/cleave.js/releases/tag/v1.2.0

**Comment by g105b** [comment]
That is excellent! Thanks for your efforts on this.
