### ISSUE TITLE
date formating issue with zero value

### ISSUE THREAD

**Issue by ahmetceylan** [nosir/cleave.js#304]
when I enter 0 for all date fields, the date I entered is converted as follows ; 
* 0000/00/0 -> 0101/01/0 -> 1010/10/10

This conversion flow looks a bit weird

**Comment by ngydat** [comment]
Same here. It's like the first number has to be different than zero

**Comment by nosir** [comment]
@ngydat `stripLeadingZeroes` is an option only applies for numeral input type.
@ahmetceylan Yea, seems there was an issue in formatting full year, fixed release: https://github.com/nosir/cleave.js/releases/tag/v1.1.6
