### ISSUE TITLE
When prefix ends with space only one character can be entered

### ISSUE THREAD

**Issue by johannesh2** [nosir/cleave.js#305]
With the following configuration only one character can be entered after prefix.
```javascript
new Cleave('.input-2', {
    prefix: 'PREFIX: '
});
```

When removing the space, more characters can be entered.

**Comment by nosir** [comment]
The default delimiter is space ` `, in your case, use a different one to avoid conflicts:
```
var cleaveCustom = new Cleave('.input-2', {
    prefix: 'PREFIX: ',
    delimiter: '|'
});
```

**Comment by nosir** [comment]
Closing this, let me know if you need further help.
