### ISSUE TITLE
Date formatting allows zeros in months and days

### ISSUE THREAD

**Issue by ozkxr** [nosir/cleave.js#31]
I don't know if a year can be 0000 but I think neigher a month or a day should be allowed to be 00.

When you type 99 for a month cleave.js automatically change it to 12 when is a month; so I suggest change to 01 when it is 0.

Also (as enhancement) would be cool if this lib change the max day allowed based on the month and the year of the input.

**Comment by nosir** [comment]
Good one, will be fixed very soon.

**Comment by nosir** [comment]
FYI, I'm on it.

**Comment by nosir** [comment]
Published, thanks guys.
