### ISSUE TITLE
Overwrite instead of insert

### ISSUE THREAD

**Issue by topcatcreatives** [nosir/cleave.js#316]
Hi there,
Firstly thank you for such a great plugin.

Im currently using cleave.js for date formatting inputs. I've noticed instead of overwriting the character at the current cursor position it inserts therefore pushing remaining chars out of the input field. When editing a date it feels unexpected e.g. editing the month number 27/03/2018, i would expect 27/04/2018, but i get 27/04/3201. I see this behaviour on the demo page for all demos.

If this is expected, would an optional parameter be possible to determine whether to insert or overwrite.

Cheers,
Wes

**Comment by nosir** [comment]
Thanks for the like @topcatcreatives 
The difficulty to apply overwrite is we need to interfere the cursor moving more, and add more calculation for the blocks contents. Not only for date type, but for all the other ones.
Unfortunately, this is not in the plan at the moment.
Cheers :)

**Comment by Bhanukamax** [comment]
> Hi there, Firstly thank you for such a great plugin.
> 
> Im currently using cleave.js for date formatting inputs. I've noticed instead of overwriting the character at the current cursor position it inserts therefore pushing remaining chars out of the input field. When editing a date it feels unexpected e.g. editing the month number 27/03/2018, i would expect 27/04/2018, but i get 27/04/3201. I see this behaviour on the demo page for all demos.
> 
> If this is expected, would an optional parameter be possible to determine whether to insert or overwrite.
> 
> Cheers, Wes

did you find a work around or a different solution for this?
