### ISSUE TITLE
Cursor position issue for prefix & noImmediatePrefix

### ISSUE THREAD

**Issue by tomaszmittlener** [nosir/cleave.js#319]
I'm facing an issue while using prefix in React. When I add the first character, the cursor jumps one place backward, so the next character goes before the first character.

Also sometimes, when I want to clear the input with backspace, some of the numbers steal remain.

Here is a demo:

JsFiffle fork:
https://jsfiddle.net/zub69ohg/2/
demo:
![2018-03-27 07 29 18](https://user-images.githubusercontent.com/24290064/37948892-7e3d177a-3192-11e8-99ae-0653676cb68c.gif)

**Comment by nosir** [comment]
hmm, seems there is something wrong with noImmediatePrefix option.

**Comment by nosir** [comment]
Oh sorry, seems I missed tagging this issue when released the fix:
https://github.com/nosir/cleave.js/releases/tag/v1.3.7
It should be fixed a while ago, closing the ticket, please let me know if you have any questions
