### ISSUE TITLE
Support of VAT formatting

### ISSUE THREAD

**Issue by dvergeylen** [nosir/cleave.js#32]
Hello,

Thank you for this very handy tool!

Wouldn't it be awesome if we also could detect V.A.T formats?
An official definition is given [here](http://ec.europa.eu/taxation_customs/vies/faq.html?locale=en#item_11) for countries of the U.E.

However, this isn't the only way VAT numbers are encoded. For instance, in Belgium, although the official format is `BE0\d{9}`, it's common to see VAT numbers encoded like the following: BE0999.999.999 (period every 3 digits), BE999.999.999 (missing leading 0) or BE999999999 (missing leading 0 but not periods).

Regex for Belgian VAT numbers would then become something like that: [[rubular permalink]](http://rubular.com/r/8JopCXTec5)

I guess we first need a discussion about common V.A.T numbers encoding practices before implementing this but this could definitely be of interest, wouldn't it?

**Comment by trjiang** [comment]
Hey @dvergeylen Looks like you are talking about VAT identification number, I guess we won't add this formatter for now.

The main reason is, this is not the general used requirement for most of the users, also to add this will increase the lib size quite a lot. In my option, the whole VATIN thing can be an individual lib :smile: see the table here: https://en.wikipedia.org/wiki/VAT_identification_number

Still thanks for proposing this, if you only wanna do something for a certain country's VATIN, it can just be like this: https://jsfiddle.net/1fz4qdf0/1/

```
// BE0999.999.999
var cleaveCustom = new Cleave('.input-custom0', {
		numericOnly: true,
		prefix: 'BE0',
    blocks: [6, 3, 3],
    delimiter: '.',
});
```

**Comment by dvergeylen** [comment]
Thank you for the feedback :simple_smile:
