### ISSUE TITLE
Mask with leading zeroes

### ISSUE THREAD

**Issue by eduo** [nosir/cleave.js#320]
I might be barking up the wrong tree, but I found out about cleave from this other, older, project:

https://github.com/digitalBush/jquery.maskedinput

My intent was to have fixed width with leading zeroes in an input field (since it's a requirement for the intended purpose) and that's the sole point of that older library. Since it points to Cleave I assumed it would be something simple.

Nonetheless, I can't find anywhere how to define such a mask. I know it must be obvious, since it's linked as a solution for the specific problem, but for the life of me I can't find anything other than how to strip those leading zeroes I want the library to put back in.

Is this just a confusion and this library doesn't handle that? The docs don't seem to specify this but it may be documented in an indirect way I'm missing.

Thanks

**Comment by alexandresebrao** [comment]
I had the same problem, so I fixed by adding the leading 0s when the field blur and remove then on focus

**Comment by nosir** [comment]
Sorry for the delay, Cleave is not an input mask lib, and this isn't meant to replace any mask library.
It only does mask with leading zero automatically for date input type, however if your case is very specific, I'm afraid it can't handle that.
Still thanks for reading the doc and spending time on it.
