### ISSUE TITLE
Odd behavior with phone Masking with errant +

### ISSUE THREAD

**Issue by zslabs** [nosir/cleave.js#322]
On the demo site, if I enter a `+` after the starting digit, it seems like I can break the phone masking. Should the `+` be restricted if it is not the first character?

<img width="652" alt="screen shot 2018-03-29 at 1 47 01 pm" src="https://user-images.githubusercontent.com/1018402/38104718-1658338e-3358-11e8-9012-4ebddbaf4082.png">

**Comment by nosir** [comment]
Released in https://github.com/nosir/cleave.js/releases/tag/v1.4.2
Cheers
