### ISSUE TITLE
Cannot import in create-react-app-typescript project

### ISSUE THREAD

**Issue by elijah-schow** [nosir/cleave.js#323]
### To reproduce:
1. Create an app with [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript):
    ```
    $ yarn global add create-react-app
    $ create-react-app my-app --scripts-version=react-scripts-ts
    ```
2. Install **cleave.js**
    ```
    $ yarn add cleave.js @types/cleave.js
    ```

3. Try to import cleave.js into a **.tsx** file as instructed in [README.md](https://github.com/nosir/cleave.js/blob/master/README.md):
    ```js
    import Cleave = require('cleave.js/react');
    ```
### Expected
Can use **cleave.js** normally.

### Actual
Compiler error:
> [ts] Import assignment cannot be used when targeting ECMAScript modules. Consider using 'import * as ns from "mod"', 'import {a} from "mod"', 'import d from "mod"', or another module format instead.
module "/node_modules/@types/cleave.js/react/index"

### Solution (Edit)

Import **'cleave.js/react'**  instead of **cleave.js**. 
```js
import * as Cleave from 'cleave.js/react';
```
I'm still going to post this in case someone else has the issue. Docs could be updated to clarify.

**Comment by kenzanboo** [comment]
this solution works great! thanks

**Comment by rbary** [comment]
Thanks for the solution :)
