### ISSUE TITLE
BR Phone numbers are wrong

### ISSUE THREAD

**Issue by khaosdoctor** [nosir/cleave.js#325]
It's been a while since all phone numbers in Brazil have 9 digits, however the phone addon is not updated to recognize all brazilian states as having 9 digits phones.

So, for instance, in Cleave if I type a São Paulo phone number like `11 123456789` it works like a charm, but with more recently updated states like Paraná `41 123456789` will not print `9` since it recognizes this prefix as a eight-number phone.

**Comment by nosir** [comment]
Ah, sorry guys, I was confused by the example @khaosdoctor present above.
Turns out you need to enter `11 987654321` not `11 123456789` for São Paulo phone number.
And yes, seems 41 not working correctly, I will update the underlying google phone lib today

**Comment by nosir** [comment]
Fixed and released in https://github.com/nosir/cleave.js/releases/tag/v1.4.6
Cheers
