### ISSUE TITLE
Number Formatting: cursor jumping

### ISSUE THREAD

**Issue by ponko2** [nosir/cleave.js#332]
If you paste a very large number from the clipboard with `numeral: true` and `numeralThousandsGroupStyle: 'thousand'` specified as options, the cursor position will be shifted after pasting.

### Steps to Reproduce
1. Open http://nosir.github.io/cleave.js/
2. Copy `1234567` to clipboard
3. Paste the content of the clipboard into the field of **Numeral formatting**

### Expected Result
When pasting values, the cursor moves to the right of the pasted content

![cursor-jumping](https://user-images.githubusercontent.com/901860/38545241-91ed5930-3ce4-11e8-8cb5-322dd9190545.gif)

**Comment by nosir** [comment]
Fixed in https://github.com/nosir/cleave.js/releases/tag/v1.3.7
Thanks
