### ISSUE TITLE
Optional number of chars in block

### ISSUE THREAD

**Issue by chrisschaub** [nosir/cleave.js#337]
Is there a way to put a min / max number of chars for a block. International phone numbers can be 1 to 3 chars as a country code prefix. I need a special international format like

+44.2342343434343

I need to be able to say a block of numbers is 1-3 chars. 

Thx.

**Comment by nosir** [comment]
Hey, unfortunately this lib doesn't support dynamic (optional) chars amount for blocks, which means before applying the settings, blocks config needs to be fixed
Thanks
