### ISSUE TITLE
inputs with prefix have cursor issue

### ISSUE THREAD

**Issue by jsegal205** [nosir/cleave.js#338]
From the http://nosir.github.io/cleave.js/, if you place your cursor to the left of the prefix and start typing you will get input text in reverse up to the length of the prefix. 

repo steps: 
1. find prefix demo
2. focus cleaved input
3. type `123456789`
4. backspace all input text only leaving prefix text
5. place cursor in front to the left of the prefix text
6. type `123456789`

expected: the text is input after the prefix in correct order

actual: the text is input after the prefix but in reverse order, up until the length of the prefix text and then the cursor stays at that point.

[video demo here](https://drive.google.com/open?id=1VaJza8Sm3nz7fcecqEgUYCfehLzSwcqc)

**Comment by nosir** [comment]
Hi, this has been fixed in v1.4.8.
It's still moving the cursor but preventing incorrect letters now.
Cheers
