### ISSUE TITLE
JCB cards beginning with 2131 or 1800 have 15 digits. 

### ISSUE THREAD

**Issue by kokoyoshi** [nosir/cleave.js#339]
JCB cards beginning with 2131 or 1800 have 15 digits. 
However this library can enter 16 digits even if it starts with them.
http://www.regular-expressions.info/creditcard.html

Or 15 digits probably do not seem to be used anymore, so it may be good to remove...
> It also appears that 1800 and 2131 for JCB are obsolete

https://en.wikipedia.org/wiki/Talk:Payment_card_number

The IIN range of JCB's card is 3528 - 3589 according to Wikipedia now.
https://en.wikipedia.org/wiki/Payment_card_number

**Comment by nosir** [comment]
Okay, will just add a JCB15 type to have the block [4, 6, 5]

**Comment by nosir** [comment]
Released in https://github.com/nosir/cleave.js/releases/tag/v1.3.6

**Comment by kokoyoshi** [comment]
I appreciate your response. :laughing:
