### ISSUE TITLE
More credit card types ?

### ISSUE THREAD

**Issue by Nuranto** [nosir/cleave.js#34]
Hi,

Have you planned to add Maestro and/or BCMC support ?

**Comment by trjiang** [comment]
Could be added, we did a bit search, couldn't find out the exact pattern for Maestro.
Do you have any reference page for it? Also for BCMC too. Thanks

**Comment by Nuranto** [comment]
Here  : http://www.richardsramblings.com/regex/credit-card-numbers/
It says ^(?:5[0678]\d\d|6304|6390|67\d\d)\d{8,15}$ for maestro

Here : http://stackoverflow.com/questions/9315647/regex-credit-card-number-tests
and Here : https://dzone.com/articles/java-regular-expressions
It says ^(5018|5020|5038|6304|6759|6761|6763)[0-9]{8,15}$

Can't find for BCMC...

**Comment by nosir** [comment]
Ok, will include maestro then, thanks.

**Comment by nosir** [comment]
FYI, I'm on it.

**Comment by nosir** [comment]
Released, thanks.

**Comment by Nuranto** [comment]
Thanks !
