### ISSUE TITLE
Why there is no jquery version?

### ISSUE THREAD

**Issue by Bighamster** [nosir/cleave.js#341]
kind of (+autoUnmask option for numeric):

```javascript
$('#price,#sum').cleave({ numeral: true, numeralThousandsGroupStyle: 'thousand', autoUnmask: true});
```

```javascript
(function($, window, undefined){ 'use strict'

  $.fn.cleave = function(opts) {

    var defaults = {autoUnmask: false},
        options = $.extend(defaults, opts || {});

    return this.each(function(){

      var cleave = new Cleave('#'+this.id, options), $this = $(this);

      $this.data('cleave-auto-unmask', options['autoUnmask']);;
      $this.data('cleave',cleave)
    });
  }

  var origGetHook, origSetHook;

  if ($.valHooks.input) {

    origGetHook = $.valHooks.input.get;
    origSetHook = $.valHooks.input.set;

  } else {

    $.valHooks.input = {};
  }

  $.valHooks.input.get = function (el) {

    var $el = $(el), cleave = $el.data('cleave');

    if( cleave ) {

      return $el.data('cleave-auto-unmask') ? cleave.getRawValue() : el.value;

    } else if( origGetHook ) {

      return origGetHook(el);

    } else {

      return undefined;
    }
  }

  $.valHooks.input.set = function (el,val) {

    var $el = $(el), cleave = $el.data('cleave');

    if( cleave ) {

      cleave.setRawValue(val);
      return $el;

    } else if( origSetHook ) {

      return origSetHook(el);

    } else {
      return undefined;
    }
  }
})(jQuery, window);
```

**Comment by sergx** [comment]
And how can i get getRawValue()
`$(".my-input").getRawValue()`

**Comment by Bighamster** [comment]
just use $(".my-input").val()

**Comment by nosir** [comment]
Nice, so I added a link in README, jQuery deserves more love than any other libs.
https://github.com/nosir/cleave.js#jquery-fn-usage

**Comment by Swizzy** [comment]
The line "var cleave = new Cleave('#'+this.id, options), $this = $(this);" should be "var cleave = new Cleave(this, options), $this = $(this);" to be fully compatible, you are otherwise assuming that whatever was passed to the JQuery function has an ID which may or may not be true

**Comment by Bighamster** [comment]
@Swizzy Thanks, you are right. I just don't remember why I needed 'id')

**Comment by willl** [comment]
Any ideas on how to get [`.destroy()`](https://github.com/nosir/cleave.js/blob/master/doc/public-methods.md#destroy) to work with this jQuery version?

Here's a [fiddle](https://jsfiddle.net/7r6hyjt2/2/) of my attempt to get this to work. 

My basic requirement is to be able to remove Cleave dynamically.

**Comment by armenio** [comment]
> Any ideas on how to get [`.destroy()`](https://github.com/nosir/cleave.js/blob/master/doc/public-methods.md#destroy) to work with this jQuery version?
> 
> Here's a [fiddle](https://jsfiddle.net/7r6hyjt2/2/) of my attempt to get this to work.
> 
> My basic requirement is to be able to remove Cleave dynamically.

```
	$('#btnRemoveCleave').on('click', function() {
  	console.log('destroy');
    abc.data('cleave').destroy();
  });
```

**Comment by armenio** [comment]
> Any ideas on how to get [`.destroy()`](https://github.com/nosir/cleave.js/blob/master/doc/public-methods.md#destroy) to work with this jQuery version?
> 
> Here's a [fiddle](https://jsfiddle.net/7r6hyjt2/2/) of my attempt to get this to work.
> 
> My basic requirement is to be able to remove Cleave dynamically.

```
$('#btnRemoveCleave').on('click', function() {
    console.log('destroy');
    abc.data('cleave').destroy();
});
```

**Comment by willl** [comment]
@armenio Thank you! That worked

**Comment by kevyworks** [comment]
Just a minor change for others.

```js
var cleave = new Cleave('#'+this.id, options), $this = $(this);
// should be
var $this = $(this), cleave = new Cleave($this.first(), options);
```

**Comment by DrYurets** [comment]
Can anyone please tell me how to import the addon for phone numbers?
