### ISSUE TITLE
how to use getRawValue() in a react component

### ISSUE THREAD

**Issue by Andriy-Kulak** [nosir/cleave.js#342]
I am trying to get the raw value on a `onBlur` event. If I use `e.target.value` or `e.target.rawValue`, get a string with the prefix, (i.e. '$3' instead of '3'). But I need a number without the prefix.

Any solutions to this? I am not sure how to use `getRawValue` feature, maybe that would help.

Thanks
```
<Cleave
   onBlur={(e)=>(console.log(e.target.rawValue))} // returns => '$3' instead of '3'
   value={3}
   style={{ maxWidth: '100px' }}
   options={{ prefix: '$' }}
   onChange={this.onChange}
/>
```

**Comment by zslabs** [comment]
I think you may need to use the `rawValueTrimPrefix` option https://github.com/nosir/cleave.js/blob/master/doc/options.md#rawvaluetrimprefix

**Comment by nosir** [comment]
Thanks @zslabs yea, that one does the trimming.
