### ISSUE TITLE
Incorrect behavior on custom delimeters of >1 character (as array)

### ISSUE THREAD

**Issue by amadare42** [nosir/cleave.js#348]
Hi. When trying to backspace multi-character delimeter, scripts behaves incorrectly.

**JsFiddle:** https://jsfiddle.net/w2vf8adm/
**Video:** https://puu.sh/AjXUC/602a244c5b.mp4

**Comment by dhawkmoon** [comment]
Hi, the same problem. Delimiters with length > 1 can't be deleted...

**Comment by nosir** [comment]
Fix released in https://github.com/nosir/cleave.js/releases/tag/v1.4.7
Your fiddle should be fixed too.
Cheers
