### ISSUE TITLE
wrong cursor position on backspace press in react numeric field

### ISSUE THREAD

**Issue by Liooo** [nosir/cleave.js#350]
[JSFiddle](https://jsfiddle.net/nosir/gLLsrxxf/)

As is shown in the GIF below, when backspace is pressed in numeric field, the cursor moves to the wrong position. Seems like this happens only in React component, as it doesn't happen in the demo page numeric example.

![cleave](https://user-images.githubusercontent.com/1630378/40038615-05063430-584e-11e8-8d32-012a36390fa2.gif)

**Comment by akeuk** [comment]
I have the same problem.

**Comment by nosir** [comment]
Fixed in https://github.com/nosir/cleave.js/releases/tag/v1.3.7
Thanks
