### ISSUE TITLE
[1.3.4] prettier-eslint is defined under dependencies in package.json

### ISSUE THREAD

**Issue by ankurk91** [nosir/cleave.js#354]
Hi,
```prettier-eslint``` is defined under dependencies in package.json
https://unpkg.com/cleave.js@1.3.4/package.json

I could not find this in the GitHub repo, seems like it was accidentally added before publishing.

Can we make sure that npm package files are synced with git repo.
May be add a `prepublishOnly` script that checks if nothing is staged.

Thanks.

**Comment by nosir** [comment]
Hi, sorry, just merged. npm publish in 1.3.5
