### ISSUE TITLE
Delimiter maxLenght not working correctly on french number

### ISSUE THREAD

**Issue by hosnimed** [nosir/cleave.js#355]
When filing a wrong french number the delimiter don't **limit**  the number of characters.

![image](https://user-images.githubusercontent.com/7532541/40845497-2715b55c-65b7-11e8-95c8-2ea6c49910ab.png)

**Comment by nosir** [comment]
Actually, this is not an issue particularly happens for FR numbers, it's calling google lib phone js underlying and if the lib doesn't present any formatting info for the wrong number, there is no way for cleave to see if it's a valid number or still waiting for validation.
I will close this for now, will add validation if google lib phone has some update for this.
Cheers.
