### ISSUE TITLE
onValueChanged callback wont get called for Android devices

### ISSUE THREAD

**Issue by ankurk91** [nosir/cleave.js#356]
Hi,

PR #328 adds an option `onValueChanged` but it is not getting called on android devices.

I found this piece of code needs to be updated.
https://github.com/nosir/cleave.js/blob/b04d5ae27027376d35d22699e21734a59b25e5e2/src/Cleave.js#L325-L332

Here is the fiddle -
https://jsfiddle.net/9vuxne7d/3/

Thanks.

**Comment by lucax88x** [comment]
@ankurk91 

Ehy, thanks for the PR, now we have another issue, that the valueChanged is called twice, maybe it's a better idea to but the rest in the else condition?
