### ISSUE TITLE
Date formatter behavior not very intuitive

### ISSUE THREAD

**Issue by Skywalker13** [nosir/cleave.js#36]
Hello,

Thanks for this lib but I'm a bit disappointed about the date formatter.

For example with: 
```js
var cleave = new Cleave('.input-element', {
    date: true,
    datePattern: ['m', 'y']
});
```

If I want `09/12`; I must type `0`, `9`, `1` and `2`
But if I type `9`, `/`, `1`, and `2`, the `/` is not handled. The `0` should be added automatically

This one is a real problem:
```js
var cleave = new Cleave('.input-element', {
    date: true,
    datePattern: ['Y', 'm', 'd']
});
```

It's very difficult to use because most users want to type for example:
`1`, `6`, `/`, `1`, `/`, `2` for `2016/01/02`

> Note that it should be possible to use `.` instead of `/` for example. Maybe other separators too.

Regards

**Comment by nosir** [comment]
9 -> 09: will be fixed here https://github.com/nosir/cleave.js/issues/16
16/1/2 -> 2016/01/02: I would suggest you use: datePattern: ['y', 'm', 'd'], so it can identify type sequence: `1` `6` `0` `1` `0` `2` the 0 here will be required.
`/` -> 'other delimiter': you can just pass `delimiter` within option param: https://github.com/nosir/cleave.js/blob/master/doc/options.md#delimiter
