### ISSUE TITLE
Exporting interface for cleave.js/react props

### ISSUE THREAD

**Issue by dybzon** [nosir/cleave.js#361]
I'm working on a project using React and Typescript. We'd love to use the cleave.js react component for various input fields. In our application we'd like to wrap the cleave.js react component in our own component to add some custom styling and functionality. 

When we do this, we'd like to re-expose the props of the cleave.js/react component from our wrapper component, allowing us to configure CleaveOptions etc. whereever we use our wrapper component. Our problem is that the Props interface from the cleave.js/react component is not exported, so our only current option is to infer it if we want to re-expose all the props.

**If you can export the Props interface from cleave.js/react I would greatly appreciate it.**

Thanks for a great library!

**Comment by dan-kez** [comment]
Hey @nosir  - I opened up a PR in the DefinitelyTyped repo to expose these props(https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30016). @sashashakun requested your 👍 before merging.

If you have a moment to look over that small PR / comment here I'd appreciate it!

**Comment by nosir** [comment]
Hey guys, is there anything I can help in the lib itself? As @dybzon specified, sounds the lib would need to expose something?
But @dan-kez sounds like already solved it?
Sorry, not a TS export here.

**Comment by nosir** [comment]
Archive this for now, cheers.
