### ISSUE TITLE
Select text in input on focus has unexpected results

### ISSUE THREAD

**Issue by tspayne87** [nosir/cleave.js#363]
To reproduce the error or describe your requirement with a jsfiddle url would be appreciated:
https://jsfiddle.net/mkv7d9wa/1/

I am attempting to select the full text when the element is focused and seems to work good except for a value of 1 element the fiddle adds '$ ' space to the field and when I add a number that would make it '$ 4' and click out and click back into the element it flashes with the select and than clears it out.  It does not do this when a prefix is not present and it does not do it if there are 2 more more elements in the field for example '$ 444' works and '$ 44' works as expected.  I am not sure if this is a bug or not.

**Comment by nosir** [comment]
Thanks, fixed in https://github.com/nosir/cleave.js/releases/tag/v1.5.8
