### ISSUE TITLE
Add option to allow spaces

### ISSUE THREAD

**Issue by jdsteinbach** [nosir/cleave.js#368]
I ran across a situation where I needed to allow spaces inside a Cleave field (in React) but spaces are disallowed by default. An `allowSpaces` option would be really helpful. I worked around it by adding this to the options for that field:
```
blocks: [99999],
delimiter: ''
```
However, an `allowSpaces` option would have been quite helpful. Thanks!

**Comment by ahahn95** [comment]
Is this still unavailable?

**Comment by rison** [comment]
What would be the use case for this? In your option, I think you don't need cleave.js for your input field.

**Comment by ahahn95** [comment]
I have a component that sometimes needs formatted input and sometimes just needs to be an input field and I don't want to put logic in to swap out the field. I ended up using @jdsteinbach's solution.

**Comment by gTutini** [comment]
+1 for this issue.
The @jdsteinbach's aproach solves the problem, but it's kinda clunky and a simple prop could do it with a more elegant way.

**Comment by mikesteiner99** [comment]
the lack of spaces delimiter makes this script useless for me, sorry

**Comment by nosir** [comment]
Space is the default delimiter, but it only takes effect when a format type option is specified, e.g. numeral, phone, blocks, etc... 
I think in your case, none of those type actually applies, so passing an empty option object actually  does re-enable spaces entering.
While your workarounds also works 👍
