### ISSUE TITLE
http://nosir.github.io/cleave.js/

### ISSUE THREAD

**Issue by vladostsk92** [nosir/cleave.js#369]
Why in your demo http://nosir.github.io/cleave.js/  "Phone number formatting" after change country, setPhoneRegionCode don't work

Because after select RU, i can type czech phone or another country phone

**Comment by nosir** [comment]
Can't reproduce
First select RU, I entered a RU number: 9223601234, it formats the number to `922 360 12 34`
Then I switched to CZ, I entered a CZ number: 7211234, it formats the number to `721 123 456`
Thanks

**Comment by nosir** [comment]
Can't reproduce
First select RU, I entered an RU number: 9223601234, it formats the number to 922 360 12 34
Then I switched to CZ, I entered a CZ number: 721123456, it formats the number to 721 123 456
Thanks
