### ISSUE TITLE
[Feature] Comma thousand numeral formatting

### ISSUE THREAD

**Issue by lnasc256** [nosir/cleave.js#375]
Cleave has a great internalization in telephone numbers. However, we don't have this internalization in numbers.
My suggestion is a new Numeral formatting style: Comma thousand.
It will act just as thousand style, but the commas are periods and the periods are commas. Some countries use this number format, like Brazil.

For example:
thousand: US$ 1,000,000.00
comma:      R$ 1.000.000,00

**Comment by aDudman** [comment]
The formatting with "." as the thousands separator and "," as the decimal marker is indeed common outside of the US, however such formatting is already supported by using this combination of options: 

 `numeral: true,
numeralDecimalMark: ',',
delimiter: '.'`

This was found in the documentation for [numeralDecimalMark](https://github.com/nosir/cleave.js/blob/master/doc/options.md#numeraldecimalmark). Having a single option to condense that is probably not impossible, but it doesn't seem necessary to me.

**Comment by lnasc256** [comment]
This is exactly what I needed. Thank you.

**Comment by dgreene1** [comment]
If anyone is looking for an easy way to map from locale to what CleaveJS neads, I think this code will be helpful:

```ts
export const localeToParts = (locale: string) => {
  const anExampleNumber = 111222333.456;
  return Intl.NumberFormat(locale)
    .formatToParts(anExampleNumber)
    .reduce(
      (prev, curr, index) => {
        if (curr.type === "decimal") {
          prev.numeralDecimalMark = curr.value;
        }
        if (curr.type === "group") {
          prev.delimiter = curr.value;
        }
        return prev;
      },
      { numeralDecimalMark: ".", delimiter: "," }
    );
};
```

But at the moment I'm using react-aria's number masking since I think it's a better experience and provides built-in locale support. I'm not sure if the code above or my decision is final though.

**Comment by malfazakki** [comment]
> The formatting with "." as the thousands separator and "," as the decimal marker is indeed common outside of the US, however such formatting is already supported by using this combination of options:
> 
> `numeral: true, numeralDecimalMark: ',', delimiter: '.'`
> 
> This was found in the documentation for [numeralDecimalMark](https://github.com/nosir/cleave.js/blob/master/doc/options.md#numeraldecimalmark). Having a single option to condense that is probably not impossible, but it doesn't seem necessary to me.

Big Thanks, Mate
