### ISSUE TITLE
Feature Req - Max Date Rage

### ISSUE THREAD

**Issue by dan-kez** [nosir/cleave.js#377]
Thanks for this awesome library!

Is there any possibility of adding a limit on the date range that is valid? Specifically, I don't want to be able to set a year like `12/31/9999`. It would be great to validate that the year is within some bounds.

**Comment by ioliva** [comment]
Maybe the ideal behaviour for the range implementation would be similar to that used when trying to type 31 days for a month with 30, or 29 days for February on a non leap year, that is, replace for the maximum/minimum as soon as a date outside the range is typed.

**Comment by nosir** [comment]
Released in https://github.com/nosir/cleave.js/releases/tag/v1.5.0
Cheers

**Comment by humodev** [comment]
There's a bug when min is not added. I get a `cannot read property split from undefined` could we have min as an optional value?

**Comment by nosir** [comment]
@humodev that issue has been fixed and released in v1.5.2. Thanks.
