### ISSUE TITLE
Raise Default Numeral Decimal Scale

### ISSUE THREAD

**Issue by wcedmisten** [nosir/cleave.js#38]
Currently the default numeral formatter only supports decimals to two digits beyond the decimal point. I think this could be improved on by raising the limit to perhaps 5 or 6. This seems to me a more reasonable default value for decimal places. 

This default could be changed in line 364 of cleave.js (within the definition of DefaultProperties):
target.numeralDecimalScale = opts.numeralDecimalScale || 2;
to
target.numeralDecimalScale = opts.numeralDecimalScale || 6;

**Comment by nosir** [comment]
The `numeral` mode is mainly designed for inputing currency/money value, so will keep it as 2.
Thanks for proposing.

**Comment by athongintel** [comment]
It's not wise to reject that propose. When implementing crypto currency, sometimes we need to provide more than 2 decimal digits number (e.x. a mount of Bitcoin to sell/buy). It's appreciated if you guys can fix this.

**Comment by nosir** [comment]
@athongintel I understand the requirement to have more than 2 digits decimal number, but why would it be a problem to pass `numeralDecimalScale` option into? like this https://github.com/nosir/cleave.js/blob/master/doc/options.md#numeraldecimalscale

**Comment by athongintel** [comment]
Yes, I found it later on. Thank you very much.
