### ISSUE TITLE
input type="number" will cause error on numeric field with thousand separator

### ISSUE THREAD

**Issue by weiloon1234** [nosir/cleave.js#381]
THE JS   
```
$('.fund-input').each(function (index, field) {
  var dc = $(this).data('decimal');
  dc = typeof dc !== 'undefined' ? dc : 5;

    new Cleave(field, {
      numeral: true,
      numeralThousandsGroupStyle: 'thousand',
      numeralDecimalScale: dc
  });
);
```

THE HTML
`<input class="form-control fund-input empty" autocomplete="off" placeholder="0.00" name="amount" type="number" value="">`

![image](https://user-images.githubusercontent.com/7457342/42726566-1070bfac-87c9-11e8-895a-73f664823ba1.png)
@nosir

**Comment by lnasc256** [comment]
Hello!

Could you try to change the input type to "tel"?

As far as I know, the "tel" input type works just like the "number", but it allows you to have commas and dots in it. It also doesn't have the right-side buttons (↑ and ↓) to increase or decrease the number. Another good thing is that this input type works just as expected in mobile, as it opens the number keyboard to the user.

`<input class="form-control fund-input empty" autocomplete="off" placeholder="0.00" name="amount" type="tel" value="">`

**Comment by natedunn** [comment]
It isn't a semantic option to use `tel` in any case other than phone numbers. The library should simply support appropriate options.

**Comment by cdiazmo** [comment]
Hi, I am having the same issue, with the "tel" keyboard the user cannot insert the dot to add decimals, so is not a valid solution for me neither.

**Comment by rshelnutt** [comment]
Tel does **_not_** work just like number. It allows for similar formats, but on android devices (at least) the period is pushed to second page and is not readily visible by users, along with several other unnecessary characters. Requiring any extra keypresses to force a solution to fit in a box is terrible practice. Going to reiterate what others have been commenting - "number" type inputs need their own coverage. tel != number

**Comment by pimskie** [comment]
> [...]The library should simply support appropriate options.

`<input type="number">` simply doesn't support input other than valid floating-point numbers.

**Comment by royipressburger** [comment]
any news on this one?

**Comment by nosir** [comment]
As indicated by @pimskie 
> `<input type="number">` simply doesn't support input other than valid floating-point numbers.
