### ISSUE TITLE
When copying to clipboard remove delimiters

### ISSUE THREAD

**Issue by fregate** [nosir/cleave.js#39]
When you copy from input field to buffer text contains delimiters
789·954·654·987
12,345,655
I don't think that is right for all the cases.
Maybe manage this behavior by some option? { copy-delimiter: [false, true] }, for example

**Comment by cht8687** [comment]
http://output.jsbin.com/ruhitifilo/1/

I will make a PR....

**Comment by nosir** [comment]
Thanks @cht8687 
Released in v0.7.0
