### ISSUE TITLE
Wrong backspace behavior around delimiters on Android

### ISSUE THREAD

**Issue by SleepWalker** [nosir/cleave.js#390]
In #147 there was a fix to properly handle backspace on old Chrome Mobile on Android.

This bug seems to be fixed in recent Chrome version, which results in false positives, when calling `Util.isAndroidBackspaceKeydown` on newer Chrome versions.

**Here are steps to reproduce:**

* enter five digits in card number input (no matter what values)
* erase the last entered digit
* try to input the new digit

**Current behavior:**

The newly entered digit will be immediately erased (because isAndroidBackspaceKeydown will return true for that digit). If you will input the next number, it will be displayed as expected

**The expected behavior:**

The entered digit should be displayed

## The fix

To fix this this bug I propose simply to test whether `charCode === 229`, because only in this case we should try to fix buggy char codes in Chrome.

**Comment by nosir** [comment]
Thanks @SleepWalker, merged and released in npm https://github.com/nosir/cleave.js/releases/tag/v1.4.4
