### ISSUE TITLE
Backspace handling on Samsung stock keyboard

### ISSUE THREAD

**Issue by SleepWalker** [nosir/cleave.js#394]
Current `Util.isAndroidBackspaceKeydown` implementation has a bug. It always one one step behind. E.g. when you press `1[backspace]2` it will bypass on the actual `backspace` press, but trigger on the `2` input, which will break the thing as described in #390 

I've found, that on Samsung S7 on stock Samsung keyboard you are getting 229 keyCodes for all the keys pressed, but for backspace you are actually getting correct keyCode === 8, but it won't be handled correctly because of the current logic for Android devices.

I propose to update the logic from #391 to completely disable `Util.isAndroidBackspaceKeydown` calls for devices on which we are getting `keyCode === 8`. It can be fixed in the following way:

```js
// if we got any charCode === 8, this means, that this device correctly
// sends backspace keys in event, so we do not need to apply any hacks
owner.hasBackspaceSupport = owner.hasBackspaceSupport || charCode === 8;
if (!owner.hasBackspaceSupport
  && Util.isAndroidBackspaceKeydown(owner.lastInputValue, currentValue)
) {
    charCode = 8;
}

owner.lastInputValue = currentValue;
```

---

I've tested on Google Nexus 5, Android 4.4, Chrome 63 on stock keyboard (device model was taken from https://github.com/facebook/react/issues/6176). I've got 229 for backspaces, but correct keyCodes for all other numeric keys. `isAndroidBackspaceKeydown` works wrong for this device too and the fix, I've wrote above won't work. The only way to fix old devices I see is to listen for keyup instead of keydown, but it will be triggered after `onInput`, which is too late.

So to fix old devices we can move backspace related logic from onInput to keyUp event handler (I'm new to your library and can not quickly answer whether it is possible) or we can leave the old devices as they are.

The fix for Samsung stock keyboard I'll submit in a new PR, but I don't know what to do with old devices. Personally I'm okay with this small edge case for users on old Androids

**Comment by nosir** [comment]
Yea, agree that we can leave old Androids, will merge your PR. Thanks @SleepWalker
