### ISSUE TITLE
CreditCardDetector and strict mode

### ISSUE THREAD

**Issue by shapeshifta78** [nosir/cleave.js#396]
Hey there, very nice work with cleave.js!

I have a question regarding the new strict mode for credit card detection:
Would it be possible to keep the spacing lengths for e.g. amex and still make it possible to enter 19 digits? When I enable strict mode and type in an amex number, the spacing is the same for every card.

See https://jsfiddle.net/shapeshifta/Lhqu62vk/5/
Thanks :+1: 

BTW: This number, for example, is supposed to be for aura credit cards, 19 digits long and has a valid Luhn: 5078601870000127985

**Comment by rison** [comment]
Sorry for the delay.
Good idea, should be an easy fix. Will update soon.

**Comment by shapeshifta78** [comment]
That would be indeed very cool! Thanks!

**Comment by nosir** [comment]
Released in https://github.com/nosir/cleave.js/releases/tag/v1.5.0
Cheers

**Comment by shapeshifta78** [comment]
Thanks a lot!
