### ISSUE TITLE
Select multiple inputs by class at once

### ISSUE THREAD

**Issue by rafael-g-s** [nosir/cleave.js#398]
Please help!
I want to use this library to select all currency inputs on a web page with the same class? and what is happening is that it only works on the first one. Please advise.

**Comment by thomas2411** [comment]
See #138  [here](https://github.com/nosir/cleave.js/issues/138#issuecomment-268024840)

**Comment by nosir** [comment]
It should throw a warning when multiple elements are query selected in DOM and advise user to create multiple instance. Will update soon.

**Comment by nosir** [comment]
Document here: https://github.com/nosir/cleave.js#usage
and throw a warning now.
Cheers
