### ISSUE TITLE
Prefix on focus

### ISSUE THREAD

**Issue by Gruven** [nosir/cleave.js#399]
The problem that [noImmediatePrefix](https://github.com/nosir/cleave.js/blob/master/doc/options.md#noimmediateprefix) only add the prefix once the user enters values. **User don't know that there would be entered prefix.** Maybe there should be an option for adding prefix on focus?
Workaround example: https://jsfiddle.net/Gruven/vb6nLjd4/

**Comment by nosir** [comment]
Makes sense to me, released in v1.5.10
Show prefix once on focus now
