### ISSUE TITLE
Phone input cut numbers

### ISSUE THREAD

**Issue by webcredo** [nosir/cleave.js#40]
I tried  to enter phone number for example +9720507777777 , but input not allow me to do this.
I tested this phone number here https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html and it showed that number is valid

**Comment by trjiang** [comment]
Is the country you trying `+972`? If yes, then the `0` before `5` needs to be removed. If you look at google phone demo page, when you include `0`, the last as you type format is incorrect.

**Comment by webcredo** [comment]
+972 is country code  but first 0 can be part of number. i think need allow it or automatically remove by input

**Comment by nosir** [comment]
@webcredo Normally with +xxx, first 0 needs to be omitted otherwise you can't dial that number from overseas.  For now, we will stick to this, only allow Google AsYouTypeFormatter format. Cheers

**Comment by webcredo** [comment]
but it not UX friendly because it input and in this country for sample half of users will input 0

**Comment by trjiang** [comment]
Does user normally put +xx, cause if it's only for national usage, we don't even want them to put `+xx`.

So if `numericOnly` is supported for phone input, would that be enough? That could prevent user from input `+`.
