### ISSUE TITLE
Documentation doesn't mention that only first element is affected

### ISSUE THREAD

**Issue by pbb72** [nosir/cleave.js#411]
The Cleave constructor takes an HTML selector to identify the input element that needs to be formatted.

HTML selectors are made to be able to select several elements at once. For example a selector ".input-numeral" means **all** elements with class "input-numeral".

However, Cleave will only format the first element from this selector. This unexpected behaviour should be documented. (Or rather, it should be changed so that all selected elements are affected.)

Demo: https://jsfiddle.net/34Lums5d/

**Comment by nosir** [comment]
Agree, it should throw a warning when multiple elements are detected. Will update soon.

**Comment by nosir** [comment]
Document here: https://github.com/nosir/cleave.js#usage
and throw a warning now.
Cheers

**Comment by ianthedev** [comment]
Can it affect all elements that match the selector? Duplicating constructors for other inputs (which needs the same feature) is inconvenient.

**Comment by nosir** [comment]
Please follow it up here: https://github.com/nosir/cleave.js/issues/485
