### ISSUE TITLE
Suffix? 

### ISSUE THREAD

**Issue by djkirby** [nosir/cleave.js#42]
I see there is a prefix option, has a suffix option been considered? I'd be happy to take a stab at it if you think it's a good idea. I think it would be good for inputs with units, "100 ft"

**Comment by djkirby** [comment]
WIP here, https://github.com/djkirby/cleave.js/tree/dk/suffix

Need to handle cursor placement

**Comment by nosir** [comment]
This has been discussed before launch, the answer is no 😄 the main reason is the suffix can always be specified out of the input field, and shouldn't be considered as part of data/model.
But feel free to play with it, thanks @djkirby

**Comment by simison** [comment]
Sorry to continue discussion at closed issue. Lemme know if I should (or shouldn't) open a new one.

I actually have an UI where I'd need `suffix` feature. It's not always great UI where suffix is far away from the value when input fields can contain both short and long values:
```
[value     --lots of space ---- ] suffix
```

We've got this:
![image](https://cloud.githubusercontent.com/assets/87168/23989379/ee62906e-0a3a-11e7-80d2-d680cc62591e.png)
User can modify blue numbers (clicking modify text just focuses to that input).

> shouldn't be considered as part of data/model.

Isn't this the case with prefix as well?

Would it be technically possible to create a Cleave plugin for suffix support?

**Comment by simison** [comment]
^ FYI @nosir I updated above comment quite a bit.

**Comment by nosir** [comment]
@simison Thanks for the comment.
We had an evaluation about this, suffix itself is a good feature, but it's just buggy with the cursor placement issue.
To fix that will bring huge amount of code and increase the codebase complicated quite much.
Hence we decided not to support it :)

**Comment by simison** [comment]
Hey! 

>To fix that will bring huge amount of code and increase the codebase complicated quite much.
>Hence we decided not to support it :)

Oh, no worries, I totally get that. I hate complicated bloated code. :-) I feel that this might be something you want to add to v-Future backlog for consideration if you ever do a complete re-write.

Thanks for considering!

**Comment by nosir** [comment]
@simison 👍

**Comment by ra-dave** [comment]
> This has been discussed before launch, the answer is no 😄 the main reason is the suffix can always be specified out of the input field, and shouldn't be considered as part of data/model. But feel free to play with it, thanks @djkirby

The same arguments could be made for prefix, yet cleave has that.
