### ISSUE TITLE
cdnjs.com stuck on v1.4.4

### ISSUE THREAD

**Issue by bridgeport** [nosir/cleave.js#421]
Thanks for this great script. FYI, cdnjs.com is still stuck on v1.4.4 when the latest is v1.4.7:
https://cdnjs.com/libraries/cleave.js

**Comment by pmk65** [comment]
You can use jsdelivr.com instead.
https://www.jsdelivr.com/package/npm/cleave.js?path=dist

**Comment by BlackFrog1** [comment]
As of Feb 23rd, 2019, cdnjs.com has the latest version.  This ticket can be closed

**Comment by nosir** [comment]
Cool, Thanks, latest v1.4.9 now 👍
