### ISSUE TITLE
Phone number doesn't format correctly if all 1s

### ISSUE THREAD

**Issue by leerob** [nosir/cleave.js#423]
My guess is that this is because of the US country code of 1, but I'm not sure. It's probably not a huge deal since this isn't a valid phone number anyway, but I thought I would document it. 

![2019-01-10 08 50 15](https://user-images.githubusercontent.com/9113740/50976248-1d9d6080-14b5-11e9-8f93-52ce90bcd7ef.gif)

**Comment by eckmLJE** [comment]
There are no US area codes that start with 1. I believe the library relies on the phone number you're entering to be valid to format it according to the specific country's requirements.

**Comment by leerob** [comment]
Makes sense. I think this is safe to close, then.
