### ISSUE TITLE
Dynamic blocks based on input length

### ISSUE THREAD

**Issue by Teja21780** [nosir/cleave.js#428]
While typing in an input field, how to change the blocks dynamically based on user input

**for example**

if input length = **5**, blocks: **[2, 3]**
if input length = **10**, blocks: **[2, 3, 5]**

**Comment by iamandrewluca** [comment]
Hacking Cleave.js

```jsx
import React from "react";
import ReactDOM from "react-dom";
import Cleave from "cleave.js/react";

function App() {
  const [value, setValue] = React.useState("");
  const ref = React.useRef();
  const lower5 = value.length < 5;

  function onChange(e) {
    setValue(e.target.value);
  }

  React.useEffect(() => {
    // 6. And trigger manual focus when our condition is meet
    // 7. Problem is that it will trigger a focus at page load
    // ref.current.focus();
  }, [lower5]);

  return (
    <Cleave
      value={value}
      onChange={onChange}
      // 5. So we get a ref to inside input
      htmlRef={hRef => (ref.current = hRef)}
      // 1. Cleave does not track option changes
      // 2. so we need to trigger a rerender when our rule is meet
      key={lower5 ? "lower5.true" : "lower5.false"}
      // 3. above key will rerender Cleave with new options
      // 4. but focus is lost
      options={{
        blocks: lower5 ? [2, 3, 5] : [3, 2, 5],
        delimiter: " ",
        uppercase: true
      }}
    />
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```
import React from "react";
import ReactDOM from "react-dom";
import Cleave from "cleave.js/react";

function App() {
  const [value, setValue] = React.useState("");
  const ref = React.useRef();
  const lower5 = value.length < 5;

  function onChange(e) {
    setValue(e.target.value);
  }

  React.useEffect(() => {
    // 6. And trigger manual focus when our condition is meet
    // 7. Problem is that it will trigger a focus at page load
    // ref.current.focus();
  }, [lower5]);

  return (
    <Cleave
      value={value}
      onChange={onChange}
      // 5. So we get a ref to inside input
      htmlRef={hRef => (ref.current = hRef)}
      // 1. Cleave does not track option changes
      // 2. so we need to trigger a rerender when our rule is meet
      key={lower5 ? "lower5.true" : "lower5.false"}
      // 3. above key will rerender Cleave with new options
      // 4. but focus is lost
      options={{
        blocks: lower5 ? [2, 3, 5] : [3, 2, 5],
        delimiter: " ",
        uppercase: true
      }}
    />
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

**Comment by iamandrewluca** [comment]
One more example with dynamic length of blocks
```js
import React from "react";
import ReactDOM from "react-dom";
import Cleave from "cleave.js/react";

function App() {
  const [value, setValue] = React.useState("");
  const ref = React.useRef();
  const delimiter = " ";
  const length = value.split(delimiter).join("").length;
  const blocksOf4 = Math.ceil((length + 1) / 4);
  const blocks = Array(blocksOf4).fill(4);

  console.log(length, blocksOf4, blocks);

  function onChange(e) {
    setValue(e.target.value);
  }

  React.useEffect(() => {
    // 6. And trigger manual focus when our condition is meet
    // 7. Problem is that it will trigger a focus at page load
    if (value.length !== 0) {
      ref.current.focus();
    }
  }, [blocksOf4, value.length]);

  return (
    <Cleave
      value={value}
      onChange={onChange}
      // 5. So we get a ref to inside input
      htmlRef={hRef => (ref.current = hRef)}
      // 1. Cleave does not track option changes
      // 2. so we need to trigger a rerender when our rule is meet
      key={blocksOf4}
      // 3. above key will rerender Cleave with new options
      // 4. but focus is lost
      options={{
        blocks,
        delimiter
      }}
    />
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**Comment by sandinosaso** [comment]
I did a PR that you may be interested where you can define dynamic blocks. This way there is no need to do workarounds: https://github.com/nosir/cleave.js/pull/572

**Comment by nosir** [comment]
Thanks for the proposal but dynamically blocks (options) updating is out of the lib's scope, comment added in PR https://github.com/nosir/cleave.js/pull/572 @iamandrewluca 's workaround looks good, thanks.
