### ISSUE TITLE
Is it possible to have AM/PM in timeFormat?

### ISSUE THREAD

**Issue by vfonic** [nosir/cleave.js#431]
I have a single input field where user can type in the time (hh:mm) and AM/PM. Would this be possible with this library?

Thanks!

**Comment by nosir** [comment]
Unfortunately, AM / PM is not supported, this is a bit hard to predict and format.
Closing this, cheers 👍

**Comment by dguettler** [comment]
@nosir isn't this a bit counter intuitive? It looks like you do support `timeFormat` which when set to `12` limits the time input to 0-12 hours. If you'd select this format option how would you distinguish 8am from 8pm?
Thanks, Daniel

**Comment by nosir** [comment]
I think this case, I'd put a selector to let user choose AM / PM :p
