### ISSUE TITLE
Found a formatting bug w/ prefix example

### ISSUE THREAD

**Issue by JAStanton** [nosir/cleave.js#433]
http://www.giphy.com/gifs/41xwtHEkhv1DJABgu4

If I put my cursor in the middle of the prefix example and start typing my cursor moves inside the prefix character by character and new characters are appending, and if I hold backspace it inserts a lot of dashes.

**Comment by DDR0** [comment]
Confirmed. Typing in prefix text totally mucks things up.

**Comment by twisterghost** [comment]
I've opened a pull request to try and fix this bug.

**Comment by nosir** [comment]
Thanks @twisterghost 
Release in https://github.com/nosir/cleave.js/releases/tag/v1.4.8
