### ISSUE TITLE
Misrepresenting usage in other Frameworks

### ISSUE THREAD

**Issue by sukima** [nosir/cleave.js#435]
Your [documentation](https://github.com/nosir/cleave.js/blob/master/doc/not-in-the-plan.md#not-in-the-plan) specifically states that React and Angular are not to be included in this library because the library is designed to be small and those concerns are left to the consumer.

And yet Both Angular and React are prominent in the feature list in the [README](https://github.com/nosir/cleave.js/blob/master/README.md#features). What doesn't Ember.js or Vue.js also get representation? Is the documentation incorrect? If a contributor were to offer a working playground and/or documentation of this library's use in other frameworks would they be merged?

**Comment by ankurk91** [comment]
https://github.com/nosir/cleave.js/blob/master/doc/not-in-the-plan.md

**Comment by sukima** [comment]
I'm am not understanding the context of the link. It is the same link provided for in the issue's description suggesting I read it. Also the context of the issue attempts to articulate how the content of that document contradicts with the main README. The question remains: **why is there a discrepancy for React and Angular but not for Vue and Ember**?

**Comment by DanielGibbsNZ** [comment]
The documentation mentions that it will not include an *Angular 2* directive or React *HoC*. The Readme feature lists mentions an *AngularJS* directive (not Angular 2) and a React *Component* (not HoC).

**Comment by nosir** [comment]
Thanks for the explanation @DanielGibbsNZ @ankurk91 
so yea, there is no discrepancy, as in the doc, it only supports Angular 1.x directive and normal React component, not HoC.
Cheers.
