### ISSUE TITLE
Any plans to port to ES6 Modules?

### ISSUE THREAD

**Issue by bahrus** [nosir/cleave.js#441]
I'm looking to make a web component wrapper around this great library.  The biggest hurdle is that the code is not using ES6 modules.  I tried running a converter ( https://github.com/jonbretman/amd-to-as6 ), but it didn't seem to do anything. 

I'm wondering if you had any plans to make the switch?  I noticed it isn't in your "not in my plan" note, so just hoping you'll consider taking it on!

**Comment by arekucr** [comment]
Would be nice to have this awesome lib as ES6 Module

**Comment by nika-begiashvili** [comment]
#449

**Comment by nosir** [comment]
Thanks for the effort @nika-begiashvili 
Released in v1.5.1 and npm published
