### ISSUE TITLE
Prefix with Phone in React not working

### ISSUE THREAD

**Issue by quic5** [nosir/cleave.js#442]
I have tried the following options both with and without React
```
{
    phone: true,
    phoneRegionCode: 'DE',
    prefix: '+49'
}
```

But it doesn't work with React as you see in this [CodePen](https://codepen.io/philipplu/pen/ZPeKaL)

However it does work without React as you can see in this [Pen](https://codepen.io/philipplu/pen/KEWmxg)

I guess it is probably a bug or am I making anything wrong?

**Comment by nosir** [comment]
Seems this was missing when deploying https://github.com/nosir/cleave.js/issues/247, fix released in https://github.com/nosir/cleave.js/releases/tag/v1.4.9
Cheers

**Comment by nosir** [comment]
Don't know how long it takes cloutflare to update 1.4.9, so your demo on codepen can work after that's updated.
https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.4.9/cleave-react.js
