### ISSUE TITLE
Error 500 when set only PL phone

### ISSUE THREAD

**Issue by Smook** [nosir/cleave.js#444]
With this setup (PL) script not working. When change to eg. DE - it works.

https://jsfiddle.net/oe8qmxw0/1/

**Comment by nosir** [comment]
I think loading that script from githubusercontent in jsfiddle is blocked.
This works for me:
https://jsfiddle.net/nosir/xwa82voz/
And I'm using cloudflare:
https://cdnjs.cloudflare.com/ajax/libs/cleave.js/1.4.9/addons/cleave-phone.pl.js
Cheers
