### ISSUE TITLE
Copy and Paste Doesn't Preserve Formatting

### ISSUE THREAD

**Issue by camiller2** [nosir/cleave.js#454]
**To reproduce:**
1. Go to https://jsfiddle.net/r2os14qk/
2. In the single field, type in '1233423432'
3. Select all the characters in the field and copy (e.g. ctrl + c)
4. Paste into any text editor

**Expected Results:**
The value pasted in the text editor is '(123) 342-3432' (with formatting preserved).

**Actual Results:**
The value pasted in the text editor is '1233423432' (without formatting preserved).

**Comment by Swizzy** [comment]
What browser are you using? that is working perfectly fine on Chrome, i copy 'n' pasted your examples, both with and without the actual formatting you expect, and it's pasted as the expected result always

**Comment by camiller2** [comment]
Weird. I'm using Chrome, Version 73.0.3683.86 (Official Build) (64-bit), on Windows 10. I just tried with a guest profile (no extensions activated), and it's reproducible.

I also just tried in Firefox, and it's reproducible.

**Comment by Swizzy** [comment]
Sorry about that, i read it the wrong way...

In any case, this line here tells you how to get what you want: https://github.com/nosir/cleave.js/blob/master/src/Cleave.js#L202

**Comment by camiller2** [comment]
Awesome, worked like a charm! Thanks!
