### ISSUE TITLE
Blocks improperly work with numeral option

### ISSUE THREAD

**Issue by kde713** [nosir/cleave.js#458]
To reproduce the error or describe your requirement with a jsfiddle url would be appreciated:
- Fork this with vanilla JS component: https://jsfiddle.net/ztn0sqh3/

`blocks` feature improperly working when `numeral` option enabled.
- Length limit doesn't applied
- Delimiter added on unexpected position

**Comment by svnv** [comment]
Try using `  numericOnly: true` option instead of the the `numeral: true` option.

https://github.com/nosir/cleave.js/blob/master/doc/options.md#numericonly

**Comment by kde713** [comment]
@svnv 
Oh... it was my misunderstanding..
Really appreciate for your help.
