### ISSUE TITLE
Negative currency amounts (numeral sign should precede the prefix)

### ISSUE THREAD

**Issue by rinogo** [nosir/cleave.js#466]
When using a prefix like "$", negative numerals appear as follows:

`$-1234.56`

Instead, we should be able to configure cleave.js such that they appear as follows, with the numeral sign *preceding* the prefix:

`-$1234.56`

I will shortly add a PR that addresses this issue by adding a `signBeforePrefix` option/property.

**Comment by nosir** [comment]
Thanks. I added a few changes for React component and released in https://github.com/nosir/cleave.js/releases/tag/v1.5.0
Cheers
