### ISSUE TITLE
Cleave React: Changing the event listeners doesn't work

### ISSUE THREAD

**Issue by zecuria** [nosir/cleave.js#477]
Steps to reproduce:
1. Mount Cleave react with an event listener (e.g. `onChange`).
2. Change the event listener while cleave is mounted.
3. Cleave uses the original event listener instead of the updated one.

React JS component: https://jsfiddle.net/zecuria/ezjystc0/

**Comment by nosir** [comment]
Thanks for the PR!
Released in v1.5.1 and npm published
