### ISSUE TITLE
What if min and max date are null in Dateformatter?

### ISSUE THREAD

**Issue by jehugaleahsa** [nosir/cleave.js#481]
Researching an issue that came up recently and it looks like it goes back to your project. I am getting an error along the lines of `Cannot read property 'split' of undefined` in my stack trace, in a method called `initDateFormatter`. Looking at the code, it is calling `new DateFormatter(pps.datePattern)` but this ctor expects 3 arguments now. I could be totally wrong, but that's what I am seeing.

https://github.com/nosir/cleave.js/blob/e50263bf6bfe65499436d12e898fb0adeb7ede16/src/shortcuts/DateFormatter.js#L9

**Comment by tcp** [comment]
Hey @jehugaleahsa, I made a PR #478 to solve this.

**Comment by olivark** [comment]
mhhhh this PR was not merged yet for 1.5.0?

**Comment by MikeGherard** [comment]
This would be a very helpful fix. As things are now, it doesn't seem possible to create a Date input using React, as even setting the dateMin and DateMax in the options will not result in them being passed through to the function properly.

**Comment by genesy** [comment]
When will this be merged? Unusable right now.

**Comment by jebax** [comment]
Unable to use the latest version because of this issue, please merge!

**Comment by craigprobus** [comment]
Please merge! We're unable to use the latest version b/c of this issue

**Comment by kvalium** [comment]
Have the same problem, split is causing an error right now, could you please merge it? :)

**Comment by nosir** [comment]
Fix released, latest version published in npm, v1.5.2
