### ISSUE TITLE
Conditional formatting

### ISSUE THREAD

**Issue by AlgyTaylor** [nosir/cleave.js#49]
Hi,

I have an input where the user is expected to enter an identifying number.  However, I am not sure what sort of number it will be, it may be of any of the forms:

E01 / 234567  (5 or 6 following characters)
M01 / 23456789 (6 or 8 following characters)
123 456 7890  (always 10 numbers)
12 34567  (2 characters followed by 4 to 8 characters)

It would be cool if I could do a regex or similar to see what the number looked like, then format it appropriately :)

**Comment by nosir** [comment]
Hey @AlgyTaylor we had a discussion about this, and decided not to add supporting for this. Basically you are trying to do dynamic pattern matching, which is a relatively unique requirement.
So will close this for now, cheers.
