### ISSUE TITLE
React uncontrolled component / defaultValue

### ISSUE THREAD

**Issue by grantbdev** [nosir/cleave.js#499]
I am using Cleave React components for uncontrolled inputs that sometimes had a default value. As suggested in #131, I was setting the default value with the `value` prop and this was working for me as expected. I believe starting in v1.5.0, editing uncontrolled inputs that were given a default value from the `value` prop no longer worked as before. I suspect this could be related to #389 / #452 where changes were made to make `value` useful for a controlled input.

Fiddles that demonstrate the change in behavior (try using backspace on the pre-filled fields):
- v1.4.10: https://jsfiddle.net/fu0ebrwv/
- v1.5.3: https://jsfiddle.net/8o2nk9fw/
- current: https://jsfiddle.net/b6vnxtw1/

Another thing I noticed is the problem goes away if the `onChange` prop is not passed. I am passing `onChange` prop to my Cleave components but not for the purpose of updating the `value` prop (like in the demo Fiddles). It may be possible for Cleave to call my `onChange` in addition to instead of as a replacement for the default `onChange` behavior. Or maybe a `defaultValue` prop should be supported for the uncontrolled use case. I am not 100% sure what is the root problem and what is the desired solution.

**Comment by MateusAntonio** [comment]
@grantbdev How did you solve the problem? I'm stucked with this now :(

**Comment by grantbdev** [comment]
@MateusAntonio The issue I was describing above appears to have been fixed. If you're on v1.5.3, upgrade if you can.
