### ISSUE TITLE
Date: Configurable delimiter

### ISSUE THREAD

**Issue by andywer** [nosir/cleave.js#50]
Hi there!

I just encountered a small issue with the date formatting. It seems that you cannot configure another delimiter. But some locales require a different delimiter (like German `dd.mm.yyyy` for example).

Would be very handy to have an option for this.

Btw: Awesome work! :)

**Comment by trjiang** [comment]
Hey @andywer thanks,

Not sure what do you mean can't configure, would this suit your requirement? https://jsfiddle.net/7af97saj/1/

**Comment by andywer** [comment]
Ohh yeah, that's exactly what I meant! :)

In this case only the documentation is missing: https://github.com/nosir/cleave.js/blob/master/doc/options.md#date

**Comment by trjiang** [comment]
Glad that works for you, we will improve the doc, thanks for pointing it out.

**Comment by nosir** [comment]
Doc has been changed.
