### ISSUE TITLE
How to use cleave.js with react-final-form?

### ISSUE THREAD

**Issue by mrjdavidfg** [nosir/cleave.js#502]
I followed this React Final Form example to use third-party components: [Third Party Components Example](https://codesandbox.io/s/40mr0v2r87) and I also checked this issue: [How to use with material-ui TextField and React-Final-Form? ](https://github.com/nosir/cleave.js/issues/335#issuecomment-402936738). 

I'm not using Material-UI components. So I did the following based on previous example:

1. Create adapter:
```
import React from 'react'
import Cleave from 'cleave.js'

export default ({ input, ...rest }) => <Cleave {...input} {...rest} />
```
2. Use it:
```
import CleaveAdapter from './CleaveAdapter.jsx'

<Field name="sample" component={CleaveAdapter} options={{numeral: true, delimiter: '-'}}/>
```
But it shows the following console error:
`TypeError: owner is undefined`
And it points to this line: [https://github.com/nosir/cleave.js/blob/996f977ff8f8397b026c3a0f99ecc225546300da/dist/cleave.js#L77](https://github.com/nosir/cleave.js/blob/996f977ff8f8397b026c3a0f99ecc225546300da/dist/cleave.js#L77)

Can you please help me?

**Comment by BOLT04** [comment]
@mrjdavidfg try importing Cleave like this:
```js
import Cleave from 'cleave.js/react'
```

**Comment by BOLT04** [comment]
Hi @mrjdavidfg, I don't know if you managed to solve your problem, but [here](https://codesandbox.io/embed/react-final-form-simple-example-3vgvb?fontsize=14) is a simple example of using cleave.js with react-final-form. Hopefully someone finds it useful 😀
