### ISSUE TITLE
Missing 8 series bin range for UnionPay

### ISSUE THREAD

**Issue by jhipps** [nosir/cleave.js#503]
Announcement from the [Vantiv](http://info.vantiv.com/rs/048-BUR-972/images/July%202018%20Enterprise%20Advantage%20Bulletin.html) processor website:

81000000 | 81099999 | UnionPay
-- | -- | --
81100000 | 81319999 | UnionPay
81320000 | 81519999 | UnionPay
81520000 | 81639999 | UnionPay
81640000 | 81719999 | UnionPay

Looks like there is support for 6 series, but 8 has not been added yet.

**Comment by leebradley** [comment]
This would be really nice, as the new card numbers were targeted to start rolling out at the beginning of this year.

**Comment by eduardoflorendo** [comment]
#546
