### ISSUE TITLE
landing have too many fonts

### ISSUE THREAD

**Issue by AliveDD** [nosir/cleave.js#51]
can we change fonts on the website?

your examples have too many fonts, and is hard to read
<img width="694" alt="screen shot 2016-07-18 at 17 01 40" src="https://cloud.githubusercontent.com/assets/5255027/16917275/f76d011c-4d11-11e6-9ef8-f10819fc1392.png">

can make page a little easier?
<img width="706" alt="screen shot 2016-07-18 at 17 02 54" src="https://cloud.githubusercontent.com/assets/5255027/16917326/39419e72-4d12-11e6-8faa-d3472bf4553f.png">

it's not as "fun" but easier to use

**Comment by nosir** [comment]
The demo page has 2 fonts loaded (only normal weight), and the font used in the input field, we also need it for the logo on top of the page. So unfortunately none of them can be removed.

Thanks for point it out 👍 will close this for now.

**Comment by AliveDD** [comment]
<img width="694" alt="f76d011c-4d11-11e6-9ef8-f10819fc1392" src="https://cloud.githubusercontent.com/assets/5255027/16952833/00ffe76a-4ddc-11e6-902d-1460a3f22b87.png">
