### ISSUE TITLE
Email address validatin using Cleave.js

### ISSUE THREAD

**Issue by begueradj** [nosir/cleave.js#516]
How do we format an email address ?
I did not find anything about this in the official documentation.

**Comment by radiantshaw** [comment]
@begueradj This is not a validation library.

**Comment by begueradj** [comment]
You are right, sorry for the terminology, I edited to replace "validate" by "format".
Thank you.

**Comment by radiantshaw** [comment]
I don't think it is possible using Cleave.js. Because Cleave formats its input based on fixed length blocks. An email doesn't have fixed length blocks.

**Comment by begueradj** [comment]
I guess you are right, thank you very much @radiantshaw :) I am closing this issue then :)
