### ISSUE TITLE
getRawValue() ignores numeralDecimalMark

### ISSUE THREAD

**Issue by ezhkov** [nosir/cleave.js#52]
I want to get value from my input and value is floating point number. I need to display it with comma as decimal mark, but when I try to get raw value from input, it gives me number without comma.
For example, I need to display 26.88 as 26,88. But when I use getRawValue() it gives me 2688

**Comment by nosir** [comment]
😭 Oops, Will fix this tonight, thanks!

**Comment by nosir** [comment]
Fixed, please check this https://jsfiddle.net/107nadL4/1/
