### ISSUE TITLE
TypeError: r is not a function

### ISSUE THREAD

**Issue by gregblass** [nosir/cleave.js#521]
My app seems to work fine in development, but in production, I get the following error: 

![image](https://user-images.githubusercontent.com/279927/66706845-38338d00-ed06-11e9-81ef-c14a81579f8a.png)

I'm using webpacker w/ Rails. I wish I had more information, but I am so stumped with this. I've been searching for hours and am just at a loss on what to do :(

**Comment by gregblass** [comment]
This is definitely an issue with my babel/webpack config. Webpacker (Rails way to use Webpack) is the most confusing thing in the world unfortunately.

**Comment by kevincolyar** [comment]
Did you find a solution for this?  I have the same issue with cleave.js and webpacker.

**Comment by gregblass** [comment]
Webpacker is not doing something out of the box to transpile cleave. I never really figured out what it was. What I ended up doing was just including the already transpiled version of cleave js in my project.

**Comment by gregblass** [comment]
Webpacker man...it is literally the worst!

**Comment by kevincolyar** [comment]
I hear ya on that one!  

I tried this but got the same error:

`
import Cleave from 'cleave.js/dist/cleave-react';
`

What was your workaround?

**Comment by gregblass** [comment]
I just put it in app/javascript/packs/cleave-react.js

And then referenced it with:

`import Cleave from 'packs/cleave-react'`

**Comment by kevincolyar** [comment]
I found if I comment out the following in my `babel.config.js` fixes the error, which makes sense because it is only used in production:

```js
      isProductionEnv && [
        require('babel-plugin-transform-react-remove-prop-types').default,
        {
          removeImport: true
        }
      ]
```

Still looking for the true fix...
