### ISSUE TITLE
Please create this lib support for ANGULAR 2/4/6/7/8

### ISSUE THREAD

**Issue by subrat7** [nosir/cleave.js#528]
To reproduce the error or describe your requirement with a jsfiddle url would be appreciated:
- Fork this with vanilla JS component: https://jsfiddle.net/nosir/kbaxx64s/
- Fork this with React JS component: https://jsfiddle.net/nosir/gLLsrxxf/

If it's mobile related, please specify your device and environment.

**Comment by nosir** [comment]
Sorry for the disappointment but that is still not in roadmap soon. Cheers.
