### ISSUE TITLE
Fix typings for "properties" field of the Cleave instances

### ISSUE THREAD

**Issue by js2me** [nosir/cleave.js#556]
Hello! I'm using Cleave.js 1.4.7 in my React components.
But sometimes I need to use only formatter without DOM usage.

And TypeScript says me that in Cleave instance not exist 'properties' field, but that's not true
![image](https://user-images.githubusercontent.com/16340911/74436704-f4998d00-4e77-11ea-9f62-cba63ceee982.png)
![image](https://user-images.githubusercontent.com/16340911/74436737-fc593180-4e77-11ea-9e68-0d05acb6e773.png)

**Comment by Kocal** [comment]
Hi,

Just for your information, I've opened https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49043 which add typings for property `properties` and it has been released in `@types/cleave.js@1.4.4`.

This issue can be closed.
