### ISSUE TITLE
1.5.4 patch update crashes React

### ISSUE THREAD

**Issue by DominicTobias-b1** [nosir/cleave.js#568]
To reproduce the error or describe your requirement with a jsfiddle url would be appreciated:
- https://codesandbox.io/s/affectionate-turing-67sbr
- Type some numbers (4+)
- Observe whole app crashes (Maximum update depth exceeded.) 😅

**Comment by sbreiler** [comment]
I'm getting the same error. But strangly it immediatly shows the error, if i set the value of the input:
```javasript
const [value, setValue] = useState('1234');
```

As long as the input length is below four, everyhing is fine. I hope this helps resolving the problem.

**Comment by izhan** [comment]
Just hit it as well. Looks like https://github.com/nosir/cleave.js/pull/527 is the offending PR

Previously `setState` (eventually hit via `owner.onInput`) within `componentWillReceiveProps` will not trigger any further updates. But https://github.com/nosir/cleave.js/pull/527 moves these `setState` calls to `componentDidUpdate`, which will create these cascading updates.

Happy to help send out a PR if needed (though I'm not too familiar with this project)

**Comment by nosir** [comment]
Would this demo below be good for your usage?
https://codesandbox.io/s/jolly-kalam-b627x
As in doc: https://github.com/nosir/cleave.js/blob/master/doc/reactjs-component-usage.md#how-to-update-raw-value

**Comment by nosir** [comment]
Even though https://github.com/nosir/cleave.js/pull/570 is still required to fix the default value issue introduced by https://github.com/nosir/cleave.js/pull/527

**Comment by nosir** [comment]
https://github.com/nosir/cleave.js/pull/570 was released in v1.5.6

**Comment by nosir** [comment]
@sbreiler and for you: https://codesandbox.io/s/zealous-cori-u6mou
