### ISSUE TITLE
Numeral with zero decimal places not working

### ISSUE THREAD

**Issue by NelsonReis** [nosir/cleave.js#57]
On a numeral, setting `numeralDecimalScale: 0` is not working and defaults to 2 decimal places.

**Comment by trjiang** [comment]
Oh, oops, we will have a look, thanks.

**Comment by NelsonReis** [comment]
Basically on the param setting it has:
`owner.numeralDecimalScale = numeralDecimalScale || 2;`

Problem with this is that `0 || 2` is `2` :cry: 

Not sure how to solve, though.

**Comment by nosir** [comment]
Published. Thanks
