### ISSUE TITLE
Documentation Request for Vue Integration

### ISSUE THREAD

**Issue by gary-goose** [nosir/cleave.js#585]
In regards to using cleave.js with vue.js, can someone demonstrate the syntax for a 'simple' HTML page?

The following documentation demonstrates how to integrate cleave.js into a full blown Vue project. https://github.com/nosir/cleave.js/blob/master/doc/vue.md

It has a beautiful code example: https://codesandbox.io/s/cleave-js-vue-integration-qmw28

One of Vue's core marketing tenant is 'Versatile' (An incrementally adoptable ecosystem that scales between a library and a full-featured framework). I feel like I'm the only person NOT using it as a full-featured framework, which will never happen with the current ASP.NET Core project I'm currently developing.

I'm very new to Vue.js and currently only need it for a few pages in my project. I keep running into this road block with code examples for Vue components\library integrations:( Is there a way to achieve the results of the full blown demo on a single page? The syntax most certainly alludes me.

Here's my failed attempt at 2 different methods to enforce an input tag to accept only numeric characters. https://jsfiddle.net/3znb4ua1/

FYI, this was posted a to StackOverflow too with no fanfare.
https://stackoverflow.com/questions/61491316/cleave-js-with-vue-js-as-simple-as-possible

**Comment by ankurk91** [comment]
https://github.com/ankurk91/vue-cleave-component
