### ISSUE TITLE
How to make prefix only appear onfocus? 

### ISSUE THREAD

**Issue by GraphicOwls** [nosir/cleave.js#605]
I would like to use the prefix for this number field only when the field is focused so the placeholder text is clear to the user. I'm still new to javascript so I am just not exactly sure how to write this.

``` javascript
// Price/Number Field
var cleave = new Cleave('.m-number', {
  numeral: true,
  numeralThousandsGroupStyle: 'thousand',
  prefix: "$"
});
```

**Comment by MuluhGodson** [comment]
From the documentation, if you have a placeholder and you want your prefix to be visible only when the user starts typing you can add this option and set it to true.:
` **noImmediatePrefix: true**`
Using your example should be:

// Price/Number Field
```
var cleave = new Cleave('.m-number', {
  numeral: true,
  numeralThousandsGroupStyle: 'thousand',
  prefix: "$",
  **noImmediatePrefix: true**
});
```

**Comment by GraphicOwls** [comment]
Ahhh, I see! Thanks so much!

**Comment by MuluhGodson** [comment]
Great. If that's done then you can close this issue and mark it as solved.
