### ISSUE TITLE
Numeral formatting doesn't support alternate decimal/thousands separators

### ISSUE THREAD

**Issue by maxxyme** [nosir/cleave.js#61]
Detailed encyclopedic article @ https://en.wikipedia.org/wiki/Decimal_mark
Examples: https://en.wikipedia.org/wiki/Decimal_mark#Examples_of_use

**Comment by maxxyme** [comment]
Plus: it seems to be limited to only 2 decimal digits.

**Comment by nosir** [comment]
https://github.com/nosir/cleave.js/blob/master/doc/options.md#numeraldecimalscale
https://github.com/nosir/cleave.js/blob/master/doc/options.md#numeraldecimalmark

**Comment by nosir** [comment]
Hope this is what you want

**Comment by maxxyme** [comment]
OK, I thought the only options were those listed in the demos: https://nosir.github.io/cleave.js/
