### ISSUE TITLE
Is it possible to keep the remaining placeholder value visible when user is typing?

### ISSUE THREAD

**Issue by Tajwebdeveloper** [nosir/cleave.js#610]
![image](https://user-images.githubusercontent.com/24293800/88513104-4d637900-d005-11ea-9dfd-c47d73763198.png)

and as user starts typing the placeholder goes away
![image](https://user-images.githubusercontent.com/24293800/88513164-69ffb100-d005-11ea-8be8-3e8b4f21a005.png)

As ux point of view it is not very intuitive as users can forget about the pattern and then again they have to go back to see the format. It would be extremely usefuly if this feature is available.

**Comment by Joshfindit** [comment]
While I agree with the usability side, it’s not a feature I’ve seen anywhere else.

It feels like it would battle for attention.

Have you considered a “traditional” tooltip that shows up when the user starts typing, and goes away once the requirement is fulfilled?

![A3ED7C98-53E5-4EAB-8D0A-A150C81590E8](https://user-images.githubusercontent.com/1937155/88546262-7dede780-cff2-11ea-8ef9-9e0557729f61.jpeg)

**Comment by Tajwebdeveloper** [comment]
Yes i can surely add tool-tip or label to avoid confusion but i really want to avoid any repetition. If you see jQuery Mask they add placeholder and its always visible https://github.com/RobinHerbots/Inputmask , but the issue is in this case the mask is quite prominent throughout which I do not need.

**Comment by frozar** [comment]
Have the possibility to make the placeholder always visible would be really great. Here is another example of project which provides this feature: https://github.com/santalu/maskara . I agree with @Tajwebdeveloper

**Comment by katerlouis** [comment]
@Tajwebdeveloper Why has this issue been closed?
