### ISSUE TITLE
Phone with 8 or 9 digits

### ISSUE THREAD

**Issue by henryavila** [nosir/cleave.js#614]
Hi, can the library mask a phone number that can have 8 or 9 digits?
ex: `(31) 91234-5678` or `(31) 1234-5678`

In Brazil The phone can be in any of this formats. The `cleave-phone.br` allow just the `(31) 1234-5678` format

**Comment by glauco-basilio** [comment]
GH way: https://jsfiddle.net/glauco_basilio/akwstj1o/6/

**Comment by henryavila** [comment]
It worked. Thanks @glauco-basilio!
