### ISSUE TITLE
React component value wrong

### ISSUE THREAD

**Issue by Nickman87** [nosir/cleave.js#71]
I'm looking into using cleave in our project so I was looking at the demo's for the React component.

In my case, I want to get the formatted result back, so I fiddled a bit with the fiddle to see what the value would be that I get after a change event, and it seems to work fine, untill you start typing more characters than the format has defined.

You can see it here: https://jsfiddle.net/3w2gajkc/

Just start typing numbers and you will see that the 11th digit isn't shown in the input field, but it _is_ shown in the value that is printed.
I've take a quick look in the react component and maybe it should just be added in the onChange handler? Instead of only inserting the rawValue, also overwrite the actual value with the correctly formatted one?

**Comment by trjiang** [comment]
Thanks @Nickman87, we will have a look soon.

**Comment by nosir** [comment]
Fixed and released in https://github.com/nosir/cleave.js/releases/tag/v0.6.2

**Comment by Nickman87** [comment]
That's quick ;) thanks
