### ISSUE TITLE
[suggestion] Hour:minutes:seconds 

### ISSUE THREAD

**Issue by ghost** [nosir/cleave.js#73]
Hello,

Cleave.js is awesome, thank you !

I would like to know if there is a possibility to add a feature for time fields.

That would be nice if we could use it like the date : 

`
var cleave = new Cleave('.input-element', {
    hour: true,
    hourPattern: ['H', 'm', 's']
});
`

Limiting H to 23, m to 59 and s to 59.

Or is there already a way I can get that behaviour ?

Thanks in advance

**Comment by nosir** [comment]
Hey, thanks for proposing.
We considered this before. However, time input is not a common requirement for website usage, so we decided not to do this.
Cheers, will close this.

**Comment by devonmather** [comment]
Bump of interest

**Comment by mazing** [comment]
Also interested

**Comment by kedarv** [comment]
If you use the custom block and delimiter options, you can get this functionality (without the input limiting).
For example:
```
  new Cleave(field, {
    delimiters: ['/', '/', ' ', ':'],
    blocks: [2, 2, 4, 2, 2]
  });
```
Will get you DD/MM/YYYY HH:ii

**Comment by FacundoGFlores** [comment]
@kedarv The problem there is `cleave.js` won't recognize the days or months pattern, so if you type `33` it would be a valid input, in contrary the `date` property will validate it for you, I mean if you type `33` it will change to `31` in the input in the case of days.

+1 for the native support.

**Comment by indivine** [comment]
+1 for time options. We run a major listings website which requires inputs for opening hours of businesses.  Please add this

**Comment by indivine** [comment]
This looks promising

**Comment by bgold0** [comment]
Would love it if there was even a custom ability to format the numbers for a 24 hour time

**Comment by dmk255** [comment]
Would also love the ability to have a time option

**Comment by nzcodarnoc** [comment]
Also interested. There are many classes of websites that would benefit a time entry format. I can think of: banking, airlines, accomodation bookings, car hire, appointment engines and calendar apps.

**Comment by nosir** [comment]
Time option released:
https://github.com/nosir/cleave.js/releases/tag/v1.4.0
https://github.com/nosir/cleave.js/blob/master/doc/options.md#time
Credit to @wex

**Comment by bgold0** [comment]
> If you use the custom block and delimiter options, you can get this functionality (without the input limiting).
> For example:
> 
> ```
>   new Cleave(field, {
>     delimiters: ['/', '/', ' ', ':'],
>     blocks: [2, 2, 4, 2, 2]
>   });
> ```
> Will get you DD/MM/YYYY HH:ii

Anyway to force numbers?

**Comment by xiexingen** [comment]
> If you use the custom block and delimiter options, you can get this functionality (without the input limiting).
> For example:
> 
> ```
>   new Cleave(field, {
>     delimiters: ['/', '/', ' ', ':'],
>     blocks: [2, 2, 4, 2, 2]
>   });
> ```
> Will get you DD/MM/YYYY HH:ii

should limit input value，exp 88/88/2018 33:33

**Comment by h0jeZvgoxFepBQ2C** [comment]
> Time option released:
> https://github.com/nosir/cleave.js/releases/tag/v1.4.0
> https://github.com/nosir/cleave.js/blob/master/doc/options.md#time
> Credit to @wex

How can I use this to get a date+time input field?
