### ISSUE TITLE
I've created an Angular Formly input based on cleave.js

### ISSUE THREAD

**Issue by eliagentili** [nosir/cleave.js#75]
Hi!
I love cleave.js and i use it in my Angular projects, so i spent a bit of time writing a custom input type for angular formly.

You can check it here: [https://www.npmjs.com/package/angular-formly-cleavejs](https://www.npmjs.com/package/angular-formly-cleavejs).

**Comment by nosir** [comment]
Thanks, @eliagentili I will keep it open.

BTW, we are working on Angular component as well :)
