### ISSUE TITLE
Date formatting issue

### ISSUE THREAD

**Issue by DrakcapJ** [nosir/cleave.js#76]
Date formatting for example MM/YY there is an issue with the zero not being prepended to the month 1 (January).
This is not the case with any other single digit month, 1 seems to be excluded and doesn't automatically format to 01.

**Comment by nosir** [comment]
You also want to put 10, 11 and 12 for month.

**Comment by DrakcapJ** [comment]
ah ok, I understand what you mean. Thank you for the response.

**Comment by nosir** [comment]
👍
