### ISSUE TITLE
NumeralFormatter formats expecting the input to have the given comma delimiter

### ISSUE THREAD

**Issue by MattiSG** [nosir/cleave.js#77]
More precisely:

```js
new Cleave(element, {
    numeral: true,
        numeralThousandsGroupStyle: 'thousand',
        numeralDecimalMark: ',',
        delimiter: ' '
    }
).properties.numeralFormatter.format('1200.24')  // yields “120 024”, should be “1 200,24”
```

I understand the sense it makes to account for the `numeralDecimalMark` to be given by the user, but it prevents setting the value to a raw JS `Number`.

- - - -

Not sure this is an issue with Cleave or with my use-case.

**Comment by nosir** [comment]
Seems you found a bug, will fix soon. Thanks
But instead of calling `.properties.numeralFormatter....`, you should call the public method `setRawValue`.

**Comment by nosir** [comment]
Ok, released, you should use it like this:
https://jsfiddle.net/4hfo4vnq/7/

**Comment by MattiSG** [comment]
Thanks @nosir for the quick reply!  😃 

I had understood how I was supposed to use the public method, but I used this private access to use Cleave as a formatter for a non-`<input>` element too. That's actually a separate issue that I described in #80.

**Comment by nosir** [comment]
Cool, so will close this as well.

Hopefully, https://github.com/nosir/cleave.js/issues/79 will help with your implementation.
