### ISSUE TITLE
Bad input behavior when using multiple characters as delimeters

### ISSUE THREAD

**Issue by caiprismo** [nosir/cleave.js#78]
Hello,

I was playing with the JSFiddle examples and when using the following configuration:

```javascript
new Cleave('.input-5', {
	uppercase: true,
    delimiters: [' | ', ' | ', ' | '],
    blocks: [3, 3, 3, 2]
});
```

After the first block is typed, the next character is inserted with a pipe '|'. If I keep typing, all the characters start being replaced with '|' too. The overall input starts to behave incorrectly.

Also seeing the same with characters like: ?, ^ and +

Example:

Characters pressed  | Result
----------------------|------------------ 
123                          |          123 &#124;
4                              |          123 &#124;  &#124;4
5                              |          123 &#124;  &#124;4 &#124; 5 
6                              |          123 &#124; &#124;&#124;&#124; &#124; 4&#124;5 &#124; 6

Thanks!

**Comment by nosir** [comment]
Cleave.js only supports one character delimiter, or delimiters, your delimiter ` | ` has spaces, so it fails. This can be an improvement ticket, I will have a look.

Cheers.

**Comment by alex-ketch** [comment]
@caiprismo One way I got around this was to cheat and use a block of `0` and a delimiter of a space ` `.
So your example would be along the lines of this:

```js
new Cleave('.input-5', {
    uppercase: true,
    delimiters: [' ', '|', ' ', ' ', '|', ' ', ' ', '|', ' '],
    blocks: [3, 0, 0, 3, 0, 0, 3, 0, 0, 2, 0]
});
```

**Comment by nosir** [comment]
Lol, brilliant! will add to the example.
