### ISSUE TITLE
Angular directive for 1.x

### ISSUE THREAD

**Issue by nosir** [nosir/cleave.js#79]
Coming soon... but for 1.x

**Comment by MattiSG** [comment]
It was actually when implementing an Angular directive that did not discriminate on its element that I came to need #80. If that's of any use to you, here is a [WIP on how I set up Cleave within a directive](https://github.com/sgmap/mes-aides-ui/blob/euros-directive/app/js/directives/euros.js). That can maybe give an idea of a slightly complex use case.

**Comment by nosir** [comment]
I'm on a cleave directive, which will only need you add it to the input field. Will let you know then if it can fit your need.

**Comment by OClement** [comment]
@nosir 
I'm actually interested in a directive as well for an internal project at work
And was starting to play with this just now but then saw you stared working on one as well

I'm curious if you'd have some kind of ETA for this? 
I was planning on seeing if I could build simple one that fits my needs in particular, but if you have something on the way and it's bound to be usable relatively soon I might focus on something else

Or if you think you have something that makes sense but don't intend on releasing it any time soon, maybe you could share what you have and I could use that as starting point?

Much appreciated

**Comment by nosir** [comment]
@OClement It's almost there, will be like this: https://jsfiddle.net/nosir/1vbeLtp8/
Just need to expose raw value and publish to master.

**Comment by ganySA** [comment]
angular2 component :+1:

**Comment by nosir** [comment]
Okay guys, Angular 1.x directive released.

Doc: https://github.com/nosir/cleave.js/blob/master/doc/angularjs-directive-usage.md
Fiddle: https://jsfiddle.net/nosir/q58sh22t/

**Comment by OClement** [comment]
@nosir 
That was quick! Thanks, seems to be working great

I took a quick look and noticed you were using $watch to achieve the desired behaviour
Not to say that this is not a good approach, but since I started working on one too I thought I would share the code as well

It is using Formatters/Parsers on ngModelController instead of watchers
Different approach, same results (although technically one might say formatters/parsers would be a bit faster but that's probably a different discussion)

It still is a work in progress: http://plnkr.co/edit/PfRVzZqL5htotsPNq8xQ?p=preview

**Comment by nosir** [comment]
@MattiSG cool, will have a look at night. Don't like watching either.

**Comment by MattiSG** [comment]
From the link I sent above:

```js
controller.$parsers.push(formatter.getRawValue.bind(formatter));
```

To use the `$formatters`, you'd need to make the formatter accessible without event binding  ;) #80

**Comment by nosir** [comment]
Okay, thanks @MattiSG @OClement , changes released:

- use formatters/parsers
- `ng-model` is binding to raw value

Doc: https://github.com/nosir/cleave.js/blob/master/doc/angularjs-directive-usage.md
Fiddle: https://jsfiddle.net/nosir/q58sh22t/
