### ISSUE TITLE
phone mask correct work?

### ISSUE THREAD

**Issue by sergey-kozlov** [nosir/cleave.js#85]
```
var cleave = new Cleave('.input-element', {
    phone: true,
    phoneRegionCode: 'RU'
});
```
With this code I can enter phone numbers like "012345678979878946465115" and "+1 111 111 1111". Why? Telephone numbers with a leading zero is not restricted at all. Phone number "+1" is not in Russia.

**Comment by trjiang** [comment]
Cleave doesn't do any mask, which means it won't restrict wrong number input.
The idea is only to add space(delimiter) for correct.
Thanks, will close this.
