### ISSUE TITLE
Copy/cut and paste behaviour enhancement

### ISSUE THREAD

**Issue by nosir** [nosir/cleave.js#89]
- IE compatible
- Fix cut behaviours (currently it doesn't cut content off)

**Comment by cht8687** [comment]
Will  window.clipboardData break the  node  build?

**Comment by nosir** [comment]
@cht8687 Guess no, `window.clipboardData` would only be called during copy and paste event, not during rendering, should be safe to use.

**Comment by cht8687** [comment]
cool, if so, I will use it and fix for IE. See this implementation:
http://otuput.jsbin.con/lahoyafude/1

if you feel ok with the code, I will submit a PR.

**Comment by nosir** [comment]
Maybe add `try` for that `window.clipboardData...` as well, just in case anything else stopped supporting that, other than that, it looks good, please submit a PR 👍

**Comment by cht8687** [comment]
Done.~

**Comment by cht8687** [comment]
maybe close this ticket? :smile:
