### ISSUE TITLE
Request: Angular 2 Directive

### ISSUE THREAD

**Issue by ganySA** [nosir/cleave.js#93]
Given the pace people are moving to Angular 2... any chance for a directive...

**Comment by nosir** [comment]
Yes, it is in the plan. Will keep this open.

**Comment by cht8687** [comment]
@ganySA  welcome PR . :smile:

**Comment by trjiang** [comment]
No PR please. Someone is already on it. Lol

**Comment by cht8687** [comment]
@trjiang Hi jeff, are you colleague of @nosir? :smile:

**Comment by kartsims** [comment]
any update on this ? should I give it a try ?

**Comment by nosir** [comment]
Sorry guys, this has been delayed.
@kartsims Feel free to try and let us know, but for now, we prefer not to bring too many cutting edge things, so probably won't merge PR for this feature.

**Comment by cht8687** [comment]
give him a chance... :smile:  @nosir

**Comment by nosir** [comment]
Sorry guys, Angular 2+, TypeScript supporting is not in the plan for `cleave.js` 1.x
It will be considered when we rewriting the lib.

Thanks.

**Comment by benjamincharity** [comment]
@judos I was hoping for this too. Not many options out there. We ended up hacking/wrapping the `text-mask-core` library in a directive. You may be able to find some inspiration from what we did:

[Mask Directive](https://github.com/GetTerminus/terminus-ui/tree/master/terminus-ui/src/mask)
[Demo](https://terminus-ui-demos.stackblitz.io/components/mask)

**Comment by cht8687** [comment]
@benjamincharity  thanks for the shared info. 
@nosir any plans for ng?
