### ISSUE TITLE
Importing angular directive with webpack

### ISSUE THREAD

**Issue by eliagentili** [nosir/cleave.js#94]
I've tried to importing the angular directive with webpack,
but i've received this error:

```
window.Cleave is not a constructor
```

i think it's because the directive use a global reference
for Cleave class.

Is there any way to correctly import the library?

**Comment by trjiang** [comment]
Hi @eliagentili, I assume you are using Angular 2? If this is the case, unfortunately it doesn't support that yet. But there is a plan and it's already in the queue.

**Comment by eliagentili** [comment]
Hi @trjiang, thanks for the reply.
I'm using Angular 1 directive, but even if I
shim the Cleave.js module, it doesn't work.

In my webpack configuration file:

```
new webpack.ProvidePlugin({
    Cleave: 'cleave.js/src/Cleave.angular',
    'window.Cleave': 'cleave.js/src/Cleave.angular',
  }),
```

and in my index

```
import 'cleave.js/src/Cleave.angular';
import 'cleave.js/src/addons/phone-type-formatter.i18n';
```

**Comment by nosir** [comment]
@eliagentili The file you imported is not a building entry. For angular usage, the only way is to refer to the compiled js.

Try to import: 'cleave.js/dist/cleave-angular' and 'cleave.js/dist/addons/cleave-phone.{country}'

**Comment by eliagentili** [comment]
Unfortunately it doesn't work.
Seems that the angular directive can't be used with webpack.

Probably you need to export the angular module and copy
this directories in the dist folder:

```
common
shortcuts
utils
```

**Comment by nosir** [comment]
Those directories are only used in building the dist files, shouldn't be ever needed again. 
Can you please share your webpack full config?

**Comment by eliagentili** [comment]
[Here](https://github.com/eliagentili/angular-redux-starter) you can find an example application that tries to import cleave.js.

1. Clone the repo
2. `npm install`
3. `npm run dev`

and see the errors in terminal.

**Comment by nosir** [comment]
Cool, will have a look later on, got sick these days.

**Comment by nosir** [comment]
@eliagentili Please try with the latest version, should be fixed in v0.7.6
In your code: `import 'cleave.js/dist/cleave.min.js';`

**Comment by nosir** [comment]
@eliagentili I've fixed the dependency error, so you can pull the latest and try to test with:
```
import 'cleave.js/dist/cleave-angular.min.js';
import 'cleave.js/dist/addons/cleave-phone.{...].js';
```
When running the project, I got errors for angular, like this one:
```
ERROR in [default] .../angular-redux-starter/src/index.ts:11:0
Cannot find name 'angular'.
```
for the line: `import * as angular from 'angular';`

So I can't go further, if you know how to resolve that please let me know.

I'm on node v6.

**Comment by eliagentili** [comment]
Ok, i'll try asap and let you know ;)

**Comment by eliagentili** [comment]
Now works pretty well.

I've updated and released my custom library for integrating cleave.js with angular-formly.

You can check it here:

[https://www.npmjs.com/package/angular-formly-cleavejs](https://www.npmjs.com/package/angular-formly-cleavejs)

It's very simple to use and brings the power of cleave.js into formly.

Thanks for the help 👍

**Comment by nosir** [comment]
Glad to know, nice repo, will definitely follow up.

**Comment by danabstude** [comment]
Sir please its not working with javascript,
