### ISSUE TITLE
When props change, the <input> is not updated

### ISSUE THREAD

**Issue by giladgo** [nosir/cleave.js#95]
This bug is best demonstrated with this fiddle:
https://jsfiddle.net/61b73gyu/2/

Try changing the input box's value, and see that the class `empty` is not removed from the input box, even though the value is not empty anymore.

This is because the props are saved in the state as `other`, but when the props change, nothing is updating the state (and therefore, no re-render).

I will open a PR which solves this.

**Comment by nosir** [comment]
Cool, thanks @giladgo
