### ISSUE TITLE
No number input type support

### ISSUE THREAD

**Issue by Supuhstar** [nosir/cleave.js#97]
I'd love to use this alongside number input delights such as min and max, and the free UI stepper.

**Comment by nosir** [comment]
The feature itself is good, but we'd keep this lib focus on the main task: formatting input content (mostly separating content and adding delimiters). Still thanks for proposing.

**Comment by Supuhstar** [comment]
Well, that's just what I want. I have a `<input type="number".>` into which users place a dollar amount, and I'm looking for ways to place that dollar sign and commas.
