### ISSUE TITLE
negative number and prefix

### ISSUE THREAD

**Issue by zenport** [nosir/cleave.js#99]
Negative number does not seem to work when using a prefix. Thanks

**Comment by nosir** [comment]
Thanks, fixed and released.

**Comment by rinogo** [comment]
Hi! When I try to enter a negative currency on the [Advanced Examples](https://jsfiddle.net/nosir/aLnhdf3z/), this doesn't seem to be fixed. Am I missing something obvious?

**Comment by rinogo** [comment]
Well, rather, I'm getting something like `$-123.45` when it should be `-$123.45`.

**Comment by rinogo** [comment]
I've created a new Issue and associated PR. See #466
